package shein

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Store struct {
	pool       *pgxpool.Pool
	shopKey    string
	schemaName string
}

type ShopSummary struct {
	ShopKey    string    `json:"shop_key"`
	ShopName   string    `json:"shop_name"`
	SchemaName string    `json:"-"`
	Enabled    bool      `json:"enabled"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type OperationRecord struct {
	Status       string
	RequestHash  string
	Response     map[string]any
	ErrorMessage string
}

var (
	ErrFulfillmentTaskNotFound = errors.New("SHEIN fulfillment task not found")
	ErrOrderNotFound           = errors.New("SHEIN order not found")
)

type FulfillmentTask struct {
	OrderNo               string     `json:"order_no"`
	ExpressChannelCode    string     `json:"express_channel_code"`
	WarehouseAddressCode  string     `json:"warehouse_address_code"`
	PlaceRequestID        string     `json:"place_request_id"`
	DeliveryNo            string     `json:"delivery_no"`
	PackageNo             string     `json:"package_no"`
	WaybillNo             string     `json:"waybill_no"`
	OrderPlaceType        *int       `json:"order_place_type,omitempty"`
	HandleResult          *int       `json:"handle_result,omitempty"`
	PrintStatus           *int       `json:"print_status,omitempty"`
	Status                string     `json:"status"`
	FailureReason         string     `json:"failure_reason,omitempty"`
	ResolutionStatus      string     `json:"resolution_status,omitempty"`
	ResolutionReason      string     `json:"resolution_reason,omitempty"`
	ResolvedAt            *time.Time `json:"resolved_at,omitempty"`
	CreatedAt             time.Time  `json:"created_at"`
	UpdatedAt             time.Time  `json:"updated_at"`
	OutboundOrderNo       string     `json:"outbound_order_no,omitempty"`
	OutboundStatus        *int       `json:"outbound_status,omitempty"`
	OutboundStatusName    string     `json:"outbound_status_name,omitempty"`
	LabelAttached         bool       `json:"label_attached,omitempty"`
	ParcelComplete        bool       `json:"parcel_complete,omitempty"`
	OMSAccount            string     `json:"oms_account,omitempty"`
	OMSOrderNo            string     `json:"oms_order_no,omitempty"`
	OMSStatusCode         *int       `json:"oms_status_code,omitempty"`
	OMSStatusKey          string     `json:"oms_status_key,omitempty"`
	OMSStatusText         string     `json:"oms_status_text,omitempty"`
	OMSWarehouseCode      string     `json:"oms_warehouse_code,omitempty"`
	OMSSyncStatus         string     `json:"oms_sync_status,omitempty"`
	OMSSyncMessage        string     `json:"oms_sync_message,omitempty"`
	OMSQueriedAt          *time.Time `json:"oms_queried_at,omitempty"`
	OrderStatus           string     `json:"order_status,omitempty"`
	OrderStatusNormalized string     `json:"order_status_normalized,omitempty"`
	LabelPrintable        bool       `json:"label_printable"`
}

var postgresSchemaPattern = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)

func NewStore(ctx context.Context, databaseURL string) (*Store, error) {
	return NewStoreForShop(ctx, databaseURL, "public", "")
}

func NewStoreForShop(ctx context.Context, databaseURL, schemaName, shopKey string) (*Store, error) {
	if strings.TrimSpace(databaseURL) == "" {
		return nil, errors.New("SHEIN_DATABASE_URL is required")
	}
	if !postgresSchemaPattern.MatchString(schemaName) {
		return nil, errors.New("invalid PostgreSQL shop schema")
	}
	poolConfig, err := pgxpool.ParseConfig(databaseURL)
	if err != nil {
		return nil, fmt.Errorf("parse SHEIN database configuration: %w", err)
	}
	poolConfig.ConnConfig.RuntimeParams["search_path"] = schemaName + ",public"
	pool, err := pgxpool.NewWithConfig(ctx, poolConfig)
	if err != nil {
		return nil, fmt.Errorf("open SHEIN database: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping SHEIN database: %w", err)
	}
	return &Store{pool: pool, shopKey: strings.TrimSpace(shopKey), schemaName: schemaName}, nil
}

func (s *Store) Close() {
	s.pool.Close()
}

func (s *Store) Migrate(ctx context.Context) error {
	_, err := s.pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS shein_go_api_operations (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			shop_key text NOT NULL,
			operation text NOT NULL,
			idempotency_key text NOT NULL,
			request_hash text NOT NULL,
			status text NOT NULL DEFAULT 'pending',
			response jsonb,
			error_message text,
			created_at timestamptz NOT NULL DEFAULT now(),
			completed_at timestamptz,
			UNIQUE (shop_key, operation, idempotency_key)
		);
		CREATE INDEX IF NOT EXISTS idx_shein_go_api_operations_created
			ON shein_go_api_operations (shop_key, created_at DESC);

		CREATE TABLE IF NOT EXISTS shein_go_order_sync_runs (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			shop_key text NOT NULL,
			status text NOT NULL,
			started_at timestamptz NOT NULL DEFAULT now(),
			completed_at timestamptz,
			fetched_orders integer NOT NULL DEFAULT 0,
			error_message text
		);
		CREATE INDEX IF NOT EXISTS idx_shein_go_order_sync_runs_shop
			ON shein_go_order_sync_runs (shop_key, id DESC);

		CREATE TABLE IF NOT EXISTS shein_go_fulfillment_tasks (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			shop_key text NOT NULL,
			order_no text NOT NULL,
			express_channel_code text NOT NULL DEFAULT '',
			warehouse_address_code text NOT NULL DEFAULT '',
			place_request_id text NOT NULL DEFAULT '',
			delivery_no text NOT NULL DEFAULT '',
			package_no text NOT NULL DEFAULT '',
			waybill_no text NOT NULL DEFAULT '',
			order_place_type integer,
			handle_result integer,
			print_status integer,
			status text NOT NULL DEFAULT 'discovered',
			failure_reason text NOT NULL DEFAULT '',
			resolution_status text NOT NULL DEFAULT '',
			resolution_reason text NOT NULL DEFAULT '',
			resolved_at timestamptz,
			created_at timestamptz NOT NULL DEFAULT now(),
			updated_at timestamptz NOT NULL DEFAULT now()
		);
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS order_place_type integer;
		ALTER TABLE shein_go_fulfillment_tasks
			DROP CONSTRAINT IF EXISTS shein_go_fulfillment_tasks_check;
		ALTER TABLE shein_go_fulfillment_tasks
			DROP CONSTRAINT IF EXISTS shein_go_fulfillment_tasks_identifier_check;
		ALTER TABLE shein_go_fulfillment_tasks
			ADD CONSTRAINT shein_go_fulfillment_tasks_identifier_check
			CHECK (place_request_id <> '' OR delivery_no <> '' OR package_no <> '');
		CREATE UNIQUE INDEX IF NOT EXISTS idx_shein_go_fulfillment_tasks_place
			ON shein_go_fulfillment_tasks (shop_key, place_request_id) WHERE place_request_id <> '';
		CREATE UNIQUE INDEX IF NOT EXISTS idx_shein_go_fulfillment_tasks_delivery
			ON shein_go_fulfillment_tasks (shop_key, delivery_no) WHERE delivery_no <> '';
		CREATE UNIQUE INDEX IF NOT EXISTS idx_shein_go_fulfillment_tasks_package
			ON shein_go_fulfillment_tasks (shop_key, order_no, package_no) WHERE package_no <> '';
		CREATE INDEX IF NOT EXISTS idx_shein_go_fulfillment_tasks_updated
			ON shein_go_fulfillment_tasks (shop_key, updated_at DESC);

		CREATE TABLE IF NOT EXISTS shein_go_auto_fulfillment_jobs (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			shop_key text NOT NULL,
			order_no text NOT NULL,
			status text NOT NULL DEFAULT 'queued',
			current_step text NOT NULL DEFAULT 'queued',
			attempts integer NOT NULL DEFAULT 0,
			shein_sku text NOT NULL DEFAULT '',
			warehouse_sku text NOT NULL DEFAULT '',
			warehouse_address_code text NOT NULL DEFAULT '',
			pre_request_id text NOT NULL DEFAULT '',
			express_channel_code text NOT NULL DEFAULT '',
			performance_cost numeric(18,4),
			currency_code text NOT NULL DEFAULT '',
			place_request_id text NOT NULL DEFAULT '',
			delivery_no text NOT NULL DEFAULT '',
			error_code text NOT NULL DEFAULT '',
			error_message text NOT NULL DEFAULT '',
			created_at timestamptz NOT NULL DEFAULT now(),
			updated_at timestamptz NOT NULL DEFAULT now(),
			started_at timestamptz,
			completed_at timestamptz,
			UNIQUE (shop_key, order_no),
			CHECK (attempts >= 0),
			CHECK (performance_cost IS NULL OR performance_cost >= 0)
		);
		CREATE INDEX IF NOT EXISTS idx_shein_go_auto_jobs_queue
			ON shein_go_auto_fulfillment_jobs (shop_key, status, updated_at DESC);

		CREATE TABLE IF NOT EXISTS shein_go_order_inventory_checks (
			shop_key text NOT NULL,
			order_no text NOT NULL,
			source_detail_fetched_at timestamptz NOT NULL,
			status text NOT NULL,
			categories text[] NOT NULL DEFAULT ARRAY[]::text[],
			reason_details text[] NOT NULL DEFAULT ARRAY[]::text[],
			error_message text NOT NULL DEFAULT '',
			checked_at timestamptz NOT NULL DEFAULT now(),
			PRIMARY KEY (shop_key, order_no),
			CHECK (status IN ('eligible', 'manual', 'failed'))
		);
		CREATE INDEX IF NOT EXISTS idx_shein_go_order_inventory_checks_queue
			ON shein_go_order_inventory_checks (shop_key, status, checked_at DESC);

		CREATE TABLE IF NOT EXISTS shein_go_bulk_fulfillment_batches (
			id text PRIMARY KEY,
			shop_key text NOT NULL,
			status text NOT NULL DEFAULT 'running',
			total_orders integer NOT NULL,
			succeeded_orders integer NOT NULL DEFAULT 0,
			failed_orders integer NOT NULL DEFAULT 0,
			failed_order_no text NOT NULL DEFAULT '',
			last_error text NOT NULL DEFAULT '',
			created_at timestamptz NOT NULL DEFAULT now(),
			updated_at timestamptz NOT NULL DEFAULT now(),
			completed_at timestamptz,
			CHECK (total_orders > 0),
			CHECK (succeeded_orders >= 0 AND failed_orders >= 0)
		);
		CREATE UNIQUE INDEX IF NOT EXISTS idx_shein_go_bulk_batches_running
			ON shein_go_bulk_fulfillment_batches (shop_key) WHERE status = 'running';
		CREATE INDEX IF NOT EXISTS idx_shein_go_bulk_batches_latest
			ON shein_go_bulk_fulfillment_batches (shop_key, created_at DESC);

		CREATE TABLE IF NOT EXISTS shein_go_bulk_fulfillment_items (
			batch_id text NOT NULL REFERENCES shein_go_bulk_fulfillment_batches(id) ON DELETE CASCADE,
			sequence_no integer NOT NULL,
			order_no text NOT NULL,
			status text NOT NULL DEFAULT 'pending',
			last_error text NOT NULL DEFAULT '',
			updated_at timestamptz NOT NULL DEFAULT now(),
			PRIMARY KEY (batch_id, order_no),
			UNIQUE (batch_id, sequence_no),
			CHECK (sequence_no > 0)
		);
		CREATE INDEX IF NOT EXISTS idx_shein_go_bulk_items_status
			ON shein_go_bulk_fulfillment_items (batch_id, status, sequence_no);

		CREATE TABLE IF NOT EXISTS shein_go_shipping_quotes (
			shop_key text NOT NULL,
			pre_request_id text NOT NULL,
			order_no text NOT NULL,
			warehouse_address_code text NOT NULL,
			quoted_at timestamptz NOT NULL DEFAULT now(),
			PRIMARY KEY (shop_key, pre_request_id)
		);
		CREATE TABLE IF NOT EXISTS shein_go_shipping_quote_candidates (
			shop_key text NOT NULL,
			pre_request_id text NOT NULL,
			express_channel_code text NOT NULL,
			express_id bigint,
			express_id_code text NOT NULL DEFAULT '',
			express_short_name text NOT NULL DEFAULT '',
			performance_cost numeric(18,4),
			currency_code text NOT NULL DEFAULT '',
			estimate_min_day integer,
			estimate_max_day integer,
			PRIMARY KEY (shop_key, pre_request_id, express_channel_code),
			FOREIGN KEY (shop_key, pre_request_id)
				REFERENCES shein_go_shipping_quotes (shop_key, pre_request_id) ON UPDATE CASCADE ON DELETE CASCADE,
			CHECK (performance_cost IS NULL OR performance_cost >= 0)
		);

		CREATE TABLE IF NOT EXISTS shein_label_purchase_choices (
			shop_key text NOT NULL,
			pre_request_id text NOT NULL,
			operation_idempotency_key text NOT NULL,
			order_no text NOT NULL,
			selection_source text NOT NULL,
			selected_price_rank smallint,
			selected_warehouse_address_code text NOT NULL,
			selected_express_id bigint,
			selected_express_id_code text NOT NULL DEFAULT '',
			selected_express_channel_code text NOT NULL,
			selected_express_short_name text NOT NULL DEFAULT '',
			selected_performance_cost numeric(18,4) NOT NULL,
			selected_currency_code text NOT NULL DEFAULT '',
			selected_estimate_min_day integer,
			selected_estimate_max_day integer,
			selection_reason text NOT NULL,
			place_request_id text NOT NULL DEFAULT '',
			delivery_no text NOT NULL DEFAULT '',
			purchased_at timestamptz NOT NULL DEFAULT now(),
			PRIMARY KEY (shop_key, pre_request_id),
			FOREIGN KEY (shop_key, pre_request_id)
				REFERENCES shein_go_shipping_quotes (shop_key, pre_request_id) ON UPDATE CASCADE,
			CHECK (selection_source IN ('automatic', 'manual')),
			CHECK (selected_price_rank IS NULL OR selected_price_rank BETWEEN 1 AND 3),
			CHECK (selected_performance_cost >= 0)
		);
		CREATE INDEX IF NOT EXISTS idx_shein_label_purchase_choices_order
			ON shein_label_purchase_choices (shop_key, order_no, purchased_at DESC);
		CREATE INDEX IF NOT EXISTS idx_shein_label_purchase_choices_operation
			ON shein_label_purchase_choices (shop_key, operation_idempotency_key);

		CREATE TABLE IF NOT EXISTS shein_label_purchase_candidates (
			shop_key text NOT NULL,
			pre_request_id text NOT NULL,
			price_rank smallint NOT NULL,
			warehouse_address_code text NOT NULL,
			express_id bigint,
			express_id_code text NOT NULL DEFAULT '',
			express_channel_code text NOT NULL,
			express_short_name text NOT NULL DEFAULT '',
			performance_cost numeric(18,4) NOT NULL,
			currency_code text NOT NULL DEFAULT '',
			estimate_min_day integer,
			estimate_max_day integer,
			is_selected boolean NOT NULL DEFAULT false,
			PRIMARY KEY (shop_key, pre_request_id, price_rank),
			FOREIGN KEY (shop_key, pre_request_id)
				REFERENCES shein_label_purchase_choices (shop_key, pre_request_id) ON UPDATE CASCADE ON DELETE CASCADE,
			CHECK (price_rank BETWEEN 1 AND 3),
			CHECK (performance_cost >= 0)
		);
		CREATE INDEX IF NOT EXISTS idx_shein_label_purchase_candidates_price
			ON shein_label_purchase_candidates (shop_key, currency_code, performance_cost, price_rank);

		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS outbound_order_no text NOT NULL DEFAULT '';
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS outbound_status integer;
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS outbound_status_name text NOT NULL DEFAULT '';
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS label_attached boolean NOT NULL DEFAULT false;
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS oms_account text NOT NULL DEFAULT '';
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS oms_order_no text NOT NULL DEFAULT '';
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS oms_status_code integer;
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS oms_status_key text NOT NULL DEFAULT '';
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS oms_status_text text NOT NULL DEFAULT '';
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS oms_warehouse_code text NOT NULL DEFAULT '';
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS oms_sync_status text NOT NULL DEFAULT '';
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS oms_sync_message text NOT NULL DEFAULT '';
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS oms_queried_at timestamptz;
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS resolution_status text NOT NULL DEFAULT '';
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS resolution_reason text NOT NULL DEFAULT '';
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS resolved_at timestamptz;
		CREATE INDEX IF NOT EXISTS idx_shein_go_fulfillment_tasks_watch
			ON shein_go_fulfillment_tasks (shop_key, oms_sync_status, outbound_order_no, updated_at DESC);

		CREATE TABLE IF NOT EXISTS shein_go_carrier_policies (
			shop_key text NOT NULL,
			oms_warehouse_key text NOT NULL,
			carrier_code text NOT NULL,
			priority integer NOT NULL CHECK (priority > 0),
			enabled boolean NOT NULL DEFAULT true,
			updated_at timestamptz NOT NULL DEFAULT now(),
			PRIMARY KEY (shop_key, oms_warehouse_key, carrier_code)
		);
		CREATE INDEX IF NOT EXISTS idx_shein_go_carrier_policies_lookup
			ON shein_go_carrier_policies (shop_key, oms_warehouse_key, priority);
		UPDATE shein_go_carrier_policies
			SET enabled = false, updated_at = now()
			WHERE oms_warehouse_key = 'ARP_EAST' AND carrier_code = 'SWIFTX' AND enabled;
	`)
	if err != nil {
		return fmt.Errorf("migrate SHEIN Go tables: %w", err)
	}
	return nil
}

func (s *Store) Credentials(ctx context.Context, shopKey string) (Credentials, error) {
	shopKey = strings.TrimSpace(shopKey)
	if shopKey == "" {
		shopKey = "default"
	}
	var credentials Credentials
	err := s.pool.QueryRow(ctx, `
		SELECT shop_key, open_key_id, secret_key, base_url
		FROM public.shein_shops
		WHERE shop_key = $1
	`, shopKey).Scan(&credentials.ShopKey, &credentials.OpenKeyID, &credentials.SecretKey, &credentials.BaseURL)
	if errors.Is(err, pgx.ErrNoRows) {
		return Credentials{}, fmt.Errorf("SHEIN shop %q is not configured", shopKey)
	}
	if err != nil {
		return Credentials{}, fmt.Errorf("load SHEIN shop credentials: %w", err)
	}
	if credentials.OpenKeyID == "" || credentials.SecretKey == "" {
		return Credentials{}, fmt.Errorf("SHEIN shop %q credentials are incomplete", shopKey)
	}
	return credentials, nil
}

func (s *Store) ListShops(ctx context.Context) ([]ShopSummary, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT shop_key, shop_name, schema_name, enabled, updated_at
		FROM public.shein_shops
		ORDER BY shop_key
	`)
	if err != nil {
		return nil, fmt.Errorf("list SHEIN shops: %w", err)
	}
	defer rows.Close()
	shops := make([]ShopSummary, 0)
	for rows.Next() {
		var shop ShopSummary
		if err := rows.Scan(&shop.ShopKey, &shop.ShopName, &shop.SchemaName, &shop.Enabled, &shop.UpdatedAt); err != nil {
			return nil, fmt.Errorf("scan SHEIN shop: %w", err)
		}
		shops = append(shops, shop)
	}
	return shops, rows.Err()
}

func (s *Store) ReserveOperation(ctx context.Context, shopKey, operation, idempotencyKey, requestHash string) (OperationRecord, bool, error) {
	if len(idempotencyKey) < 8 || len(idempotencyKey) > 200 {
		return OperationRecord{}, false, errors.New("Idempotency-Key must contain between 8 and 200 characters")
	}
	tag, err := s.pool.Exec(ctx, `
		INSERT INTO shein_go_api_operations (shop_key, operation, idempotency_key, request_hash)
		VALUES ($1, $2, $3, $4)
		ON CONFLICT DO NOTHING
	`, shopKey, operation, idempotencyKey, requestHash)
	if err != nil {
		return OperationRecord{}, false, fmt.Errorf("reserve SHEIN operation: %w", err)
	}
	if tag.RowsAffected() == 1 {
		return OperationRecord{Status: "pending", RequestHash: requestHash}, true, nil
	}
	var record OperationRecord
	var responseJSON []byte
	err = s.pool.QueryRow(ctx, `
		SELECT status, request_hash, COALESCE(response, '{}'::jsonb), COALESCE(error_message, '')
		FROM shein_go_api_operations
		WHERE shop_key = $1 AND operation = $2 AND idempotency_key = $3
	`, shopKey, operation, idempotencyKey).Scan(&record.Status, &record.RequestHash, &responseJSON, &record.ErrorMessage)
	if err != nil {
		return OperationRecord{}, false, fmt.Errorf("load reserved SHEIN operation: %w", err)
	}
	if record.RequestHash != requestHash {
		return OperationRecord{}, false, errors.New("Idempotency-Key was already used with a different request")
	}
	if len(responseJSON) > 0 {
		_ = json.Unmarshal(responseJSON, &record.Response)
	}
	return record, false, nil
}

func (s *Store) CompleteOperation(ctx context.Context, shopKey, operation, idempotencyKey string, response map[string]any) error {
	encoded, err := json.Marshal(response)
	if err != nil {
		return fmt.Errorf("encode SHEIN operation response: %w", err)
	}
	_, err = s.pool.Exec(ctx, `
		UPDATE shein_go_api_operations
		SET status = 'completed', response = $4::jsonb, completed_at = now(), error_message = NULL
		WHERE shop_key = $1 AND operation = $2 AND idempotency_key = $3
	`, shopKey, operation, idempotencyKey, encoded)
	if err != nil {
		return fmt.Errorf("complete SHEIN operation: %w", err)
	}
	return nil
}

func (s *Store) UpsertFulfillmentTask(ctx context.Context, shopKey string, task FulfillmentTask) error {
	shopKey = strings.TrimSpace(shopKey)
	task.OrderNo = strings.TrimSpace(task.OrderNo)
	task.PlaceRequestID = strings.TrimSpace(task.PlaceRequestID)
	task.DeliveryNo = strings.TrimSpace(task.DeliveryNo)
	task.PackageNo = strings.TrimSpace(task.PackageNo)
	if shopKey == "" || task.OrderNo == "" || task.PlaceRequestID == "" && task.DeliveryNo == "" && task.PackageNo == "" {
		return errors.New("shop, order and a fulfillment identifier are required for a fulfillment task")
	}
	if task.Status == "" {
		task.Status = "discovered"
	}
	query := `
		WITH updated AS (
			UPDATE shein_go_fulfillment_tasks
			SET order_no = $2,
				express_channel_code = COALESCE(NULLIF($3, ''), express_channel_code),
				warehouse_address_code = COALESCE(NULLIF($4, ''), warehouse_address_code),
				place_request_id = COALESCE(NULLIF($5, ''), place_request_id),
				delivery_no = COALESCE(NULLIF($6, ''), delivery_no),
				package_no = COALESCE(NULLIF($7, ''), package_no),
				waybill_no = COALESCE(NULLIF($8, ''), waybill_no),
				order_place_type = COALESCE($9, order_place_type),
				handle_result = COALESCE($10, handle_result),
				print_status = COALESCE($11, print_status),
				status = CASE
					WHEN resolution_status <> '' THEN status
					WHEN $12 = 'discovered' AND status IN ('placed', 'checking', 'confirming', 'ready', 'label_ready', 'failed') THEN status
					ELSE COALESCE(NULLIF($12, ''), status)
				END,
				failure_reason = $13,
				updated_at = now()
			WHERE shop_key = $1 AND (
				($5 <> '' AND place_request_id = $5)
				OR ($6 <> '' AND delivery_no = $6)
				OR ($7 <> '' AND order_no = $2 AND package_no = $7)
			)
			RETURNING id
		)
		INSERT INTO shein_go_fulfillment_tasks (
			shop_key, order_no, express_channel_code, warehouse_address_code,
			place_request_id, delivery_no, package_no, waybill_no,
			order_place_type, handle_result, print_status, status, failure_reason
		)
		SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
		WHERE NOT EXISTS (SELECT 1 FROM updated)
		ON CONFLICT DO NOTHING
	`
	if _, err := s.pool.Exec(ctx, query,
		shopKey, task.OrderNo, task.ExpressChannelCode, task.WarehouseAddressCode,
		task.PlaceRequestID, task.DeliveryNo, task.PackageNo, task.WaybillNo,
		task.OrderPlaceType, task.HandleResult, task.PrintStatus, task.Status, task.FailureReason,
	); err != nil {
		return fmt.Errorf("upsert SHEIN fulfillment task: %w", err)
	}
	return nil
}

func (s *Store) UpdateFulfillmentTaskResult(
	ctx context.Context,
	shopKey, placeRequestID, deliveryNo, expressChannelCode, warehouseAddressCode, status, failureReason string,
	handleResult, printStatus *int,
) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE shein_go_fulfillment_tasks
		SET place_request_id = COALESCE(NULLIF($2, ''), place_request_id),
			delivery_no = COALESCE(NULLIF($3, ''), delivery_no),
			express_channel_code = COALESCE(NULLIF($4, ''), express_channel_code),
			warehouse_address_code = COALESCE(NULLIF($5, ''), warehouse_address_code),
			handle_result = COALESCE($6, handle_result),
			print_status = COALESCE($7, print_status),
			status = CASE
				WHEN resolution_status <> '' THEN status
				ELSE COALESCE(NULLIF($8, ''), status)
			END,
			failure_reason = $9,
			updated_at = now()
		WHERE shop_key = $1
			AND (($2 <> '' AND place_request_id = $2) OR ($3 <> '' AND delivery_no = $3))
	`, shopKey, placeRequestID, deliveryNo, expressChannelCode, warehouseAddressCode,
		handleResult, printStatus, status, failureReason)
	if err != nil {
		return fmt.Errorf("update SHEIN fulfillment task result: %w", err)
	}
	return nil
}

func (s *Store) MarkFulfillmentTaskLabelReady(
	ctx context.Context,
	shopKey, deliveryNo, orderNo string,
	packageNos []string,
) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE shein_go_fulfillment_tasks
		SET status = 'label_ready', print_status = 2, updated_at = now()
		WHERE shop_key = $1 AND resolution_status = '' AND (
			($2 <> '' AND delivery_no = $2)
			OR ($3 <> '' AND order_no = $3 AND package_no = ANY($4::text[]))
		)
	`, shopKey, deliveryNo, orderNo, packageNos)
	if err != nil {
		return fmt.Errorf("mark SHEIN fulfillment task label ready: %w", err)
	}
	return nil
}

func (s *Store) LatestFulfillmentTask(ctx context.Context, shopKey, orderNo string) (FulfillmentTask, error) {
	orderNo = strings.TrimSpace(orderNo)
	if shopKey == "" || orderNo == "" {
		return FulfillmentTask{}, ErrFulfillmentTaskNotFound
	}
	row := s.pool.QueryRow(ctx, fulfillmentTaskSelect+`
		WHERE shop_key = $1 AND order_no = $2
		ORDER BY
			CASE status
				WHEN 'label_ready' THEN 0
				WHEN 'ready' THEN 1
				WHEN 'confirming' THEN 2
				WHEN 'checking' THEN 3
				WHEN 'placed' THEN 4
				ELSE 5
			END,
			updated_at DESC
		LIMIT 1
	`, shopKey, orderNo)
	task, err := scanFulfillmentTask(row)
	if errors.Is(err, pgx.ErrNoRows) {
		return FulfillmentTask{}, ErrFulfillmentTaskNotFound
	}
	if err != nil {
		return FulfillmentTask{}, fmt.Errorf("load SHEIN fulfillment task: %w", err)
	}
	return task, nil
}

type ParcelWatchUpdate struct {
	OutboundOrderNo    string
	OutboundStatus     *int
	OutboundStatusName string
	LabelAttached      bool
	OMSAccount         string
	OMSOrderNo         string
	OMSStatusCode      *int
	OMSStatusKey       string
	OMSStatusText      string
	OMSWarehouseCode   string
	OMSSyncStatus      string
	OMSSyncMessage     string
}

func (s *Store) SaveParcelWatch(ctx context.Context, shopKey, orderNo string, update ParcelWatchUpdate) error {
	orderNo = strings.TrimSpace(orderNo)
	if shopKey == "" || orderNo == "" {
		return ErrFulfillmentTaskNotFound
	}
	message := strings.TrimSpace(update.OMSSyncMessage)
	if len(message) > 500 {
		message = message[:500]
	}
	tag, err := s.pool.Exec(ctx, `
		UPDATE shein_go_fulfillment_tasks
		SET outbound_order_no = COALESCE(NULLIF($3, ''), outbound_order_no),
			outbound_status = COALESCE($4, outbound_status),
			outbound_status_name = COALESCE(NULLIF($5, ''), outbound_status_name),
			label_attached = $6,
			oms_account = COALESCE(NULLIF($7, ''), oms_account),
			oms_order_no = COALESCE(NULLIF($8, ''), oms_order_no),
			oms_status_code = $9,
			oms_status_key = COALESCE(NULLIF($10, ''), oms_status_key),
			oms_status_text = COALESCE(NULLIF($11, ''), oms_status_text),
			oms_warehouse_code = COALESCE(NULLIF($12, ''), oms_warehouse_code),
			oms_sync_status = CASE
				WHEN $13 <> '' THEN $13
				ELSE oms_sync_status
			END,
			oms_sync_message = $14,
			oms_queried_at = now(),
			updated_at = now()
		WHERE shop_key = $1 AND order_no = $2 AND resolution_status = ''
			AND updated_at = (
				SELECT max(updated_at) FROM shein_go_fulfillment_tasks
				WHERE shop_key = $1 AND order_no = $2
			)
	`, shopKey, orderNo, strings.TrimSpace(update.OutboundOrderNo), update.OutboundStatus,
		strings.TrimSpace(update.OutboundStatusName), update.LabelAttached,
		strings.TrimSpace(update.OMSAccount), strings.TrimSpace(update.OMSOrderNo),
		update.OMSStatusCode, strings.TrimSpace(update.OMSStatusKey),
		strings.TrimSpace(update.OMSStatusText), strings.TrimSpace(update.OMSWarehouseCode),
		strings.TrimSpace(update.OMSSyncStatus), message)
	if err != nil {
		return fmt.Errorf("save SHEIN parcel watch: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrFulfillmentTaskNotFound
	}
	return nil
}

// MarkFulfillmentTaskUnprintable prevents a permanently invalid package from
// being selected by the warehouse watcher for another label retrieval attempt.
func (s *Store) MarkFulfillmentTaskUnprintable(ctx context.Context, shopKey, orderNo, reason string) error {
	shopKey = strings.TrimSpace(shopKey)
	orderNo = strings.TrimSpace(orderNo)
	reason = strings.TrimSpace(reason)
	if shopKey == "" || orderNo == "" {
		return ErrFulfillmentTaskNotFound
	}
	if reason == "" {
		reason = "SHEIN 包裹已失效，不能打印面单"
	}
	tag, err := s.pool.Exec(ctx, `
		UPDATE shein_go_fulfillment_tasks
		SET status = 'failed', failure_reason = $3, updated_at = now()
		WHERE shop_key = $1 AND order_no = $2 AND resolution_status = ''
			AND updated_at = (
				SELECT max(updated_at) FROM shein_go_fulfillment_tasks
				WHERE shop_key = $1 AND order_no = $2
			)
	`, shopKey, orderNo, reason)
	if err != nil {
		return fmt.Errorf("mark SHEIN fulfillment task unprintable: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrFulfillmentTaskNotFound
	}
	return nil
}

func validFulfillmentResolutionStatus(status string) bool {
	switch strings.TrimSpace(status) {
	case "manually_fulfilled", "cancelled", "not_required", "other":
		return true
	default:
		return false
	}
}

// ResolveFulfillmentTask ends local fulfillment handling for one package after
// an operator has recorded its final outcome. It does not alter the SHEIN order.
func (s *Store) ResolveFulfillmentTask(
	ctx context.Context,
	shopKey, orderNo, placeRequestID, deliveryNo, packageNo, resolutionStatus, resolutionReason string,
) error {
	shopKey = strings.TrimSpace(shopKey)
	orderNo = strings.TrimSpace(orderNo)
	placeRequestID = strings.TrimSpace(placeRequestID)
	deliveryNo = strings.TrimSpace(deliveryNo)
	packageNo = strings.TrimSpace(packageNo)
	resolutionStatus = strings.TrimSpace(resolutionStatus)
	resolutionReason = strings.TrimSpace(resolutionReason)
	if shopKey == "" || orderNo == "" || (placeRequestID == "" && deliveryNo == "" && packageNo == "") {
		return ErrFulfillmentTaskNotFound
	}
	if !validFulfillmentResolutionStatus(resolutionStatus) {
		return errors.New("invalid fulfillment final status")
	}
	if resolutionReason == "" {
		return errors.New("fulfillment resolution reason is required")
	}
	if len(resolutionReason) > 500 {
		return errors.New("fulfillment resolution reason must not exceed 500 characters")
	}

	tag, err := s.pool.Exec(ctx, `
		UPDATE shein_go_fulfillment_tasks
		SET status = 'resolved',
			resolution_status = $6,
			resolution_reason = $7,
			resolved_at = now(),
			oms_sync_status = 'manual_resolved',
			oms_sync_message = '人工关闭：' || $7,
			updated_at = now()
		WHERE shop_key = $1 AND order_no = $2 AND (
			($5 <> '' AND package_no = $5)
			OR ($5 = '' AND $4 <> '' AND delivery_no = $4)
			OR ($5 = '' AND $4 = '' AND $3 <> '' AND place_request_id = $3)
		)
	`, shopKey, orderNo, placeRequestID, deliveryNo, packageNo, resolutionStatus, resolutionReason)
	if err != nil {
		return fmt.Errorf("resolve SHEIN fulfillment task: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return ErrFulfillmentTaskNotFound
	}
	return nil
}

func (s *Store) ListWarehouseWatchTasks(ctx context.Context, shopKey string, limit int) ([]FulfillmentTask, error) {
	if limit < 1 || limit > 200 {
		limit = 80
	}
	rows, err := s.pool.Query(ctx, fulfillmentTaskSelect+`
		WHERE shop_key = $1
			AND status IN ('label_ready', 'ready')
			AND NOT (
				COALESCE(oms_sync_status, '') = 'verified'
				AND COALESCE(oms_status_key, '') IN ('shipped', 'delivered', 'outbound')
			)
			AND NOT (
				COALESCE(oms_sync_status, '') = 'manual_required'
				AND outbound_order_no = ''
				AND NOT (warehouse_address_code = ANY($3))
			)
			AND (
				outbound_order_no <> ''
				OR COALESCE(oms_sync_status, '') <> ''
				OR warehouse_address_code = ANY($4)
			)
		ORDER BY
			CASE WHEN oms_queried_at IS NULL THEN 0 ELSE 1 END,
			oms_queried_at ASC NULLS FIRST,
			updated_at DESC
		LIMIT $2
	`, shopKey, limit, manualParcelWarehouseAddressCodes(), warehouseWatchAddressCodes())
	if err != nil {
		return nil, fmt.Errorf("list SHEIN warehouse watch tasks: %w", err)
	}
	defer rows.Close()
	return scanFulfillmentTasks(rows)
}

func (s *Store) ListOMSPlatformOrders(ctx context.Context, shopKey, status string, limit int) ([]FulfillmentTask, error) {
	if limit < 1 || limit > 500 {
		limit = 200
	}
	filter, err := omsPlatformOrderFilter(status)
	if err != nil {
		return nil, err
	}
	rows, err := s.pool.Query(ctx, fulfillmentTaskSelect+`
		WHERE shop_key = $1 AND (`+filter+`)
		ORDER BY COALESCE(oms_queried_at, updated_at) DESC
		LIMIT $2
	`, shopKey, limit)
	if err != nil {
		return nil, fmt.Errorf("list SHEIN OMS platform orders: %w", err)
	}
	defer rows.Close()
	return scanFulfillmentTasks(rows)
}

func (s *Store) CountOMSPlatformOrders(ctx context.Context, shopKey string) (map[string]int, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT
			COUNT(*) FILTER (WHERE `+omsPlatformOrderStatusMatch("0")+`) AS status_0,
			COUNT(*) FILTER (WHERE `+omsPlatformOrderStatusMatch("1")+`) AS status_1,
			COUNT(*) FILTER (WHERE `+omsPlatformOrderStatusMatch("2")+`) AS status_2,
			COUNT(*) FILTER (WHERE `+omsPlatformOrderStatusMatch("3")+`) AS status_3,
			COUNT(*) FILTER (WHERE `+omsPlatformOrderStatusMatch("missing")+`) AS missing,
			COUNT(*) FILTER (WHERE `+omsPlatformOrderStatusMatch("manual_required")+`) AS manual_required
		FROM shein_go_fulfillment_tasks
		WHERE shop_key = $1
			AND (`+omsPlatformOrderStatusMatch("all")+`)
	`, shopKey)
	if err != nil {
		return nil, fmt.Errorf("count SHEIN OMS platform orders: %w", err)
	}
	defer rows.Close()
	var status0, status1, status2, status3, missing, manualRequired int
	if !rows.Next() {
		return map[string]int{"0": 0, "1": 0, "2": 0, "3": 0, "missing": 0, "manual_required": 0}, rows.Err()
	}
	if err := rows.Scan(&status0, &status1, &status2, &status3, &missing, &manualRequired); err != nil {
		return nil, fmt.Errorf("scan SHEIN OMS platform order counts: %w", err)
	}
	return map[string]int{
		"0": status0, "1": status1, "2": status2, "3": status3,
		"missing": missing, "manual_required": manualRequired,
	}, rows.Err()
}

func omsDisplayedStatusExpr() string {
	return `CASE WHEN outbound_order_no <> '' THEN outbound_status ELSE oms_status_code END`
}

func omsPlatformOrderFilter(status string) (string, error) {
	filter := omsPlatformOrderStatusMatch(status)
	if filter == "" {
		return "", errors.New("unknown SHEIN OMS platform order status")
	}
	return filter, nil
}

func omsPlatformOrderStatusMatch(status string) string {
	const watched = `(outbound_order_no <> '' OR COALESCE(oms_sync_status, '') <> '')`
	switch strings.TrimSpace(status) {
	case "", "all":
		return watched
	case "0":
		return watched + ` AND ` + omsDisplayedStatusExpr() + ` = 0`
	case "1":
		return watched + ` AND ` + omsDisplayedStatusExpr() + ` = 1`
	case "2":
		return watched + ` AND ` + omsDisplayedStatusExpr() + ` = 2`
	case "3":
		return watched + ` AND ` + omsDisplayedStatusExpr() + ` = 3`
	case "missing":
		return `oms_sync_status IN ('waiting_sync', 'querying', 'failed') AND ` + omsDisplayedStatusExpr() + ` IS NULL`
	case "manual_required":
		return `oms_sync_status = 'manual_required' AND outbound_order_no = ''`
	default:
		return ""
	}
}

const fulfillmentTaskSelect = `SELECT order_no, express_channel_code, warehouse_address_code,
	place_request_id, delivery_no, package_no, waybill_no,
	order_place_type, handle_result, print_status, status, failure_reason, resolution_status, resolution_reason, resolved_at, created_at, updated_at,
	outbound_order_no, outbound_status, outbound_status_name, label_attached,
	oms_account, oms_order_no, oms_status_code, oms_status_key, oms_status_text,
	oms_warehouse_code, oms_sync_status, oms_sync_message, oms_queried_at
	FROM shein_go_fulfillment_tasks`

type fulfillmentTaskScanner interface {
	Scan(dest ...any) error
}

func scanFulfillmentTask(scanner fulfillmentTaskScanner) (FulfillmentTask, error) {
	var task FulfillmentTask
	err := scanner.Scan(
		&task.OrderNo, &task.ExpressChannelCode, &task.WarehouseAddressCode,
		&task.PlaceRequestID, &task.DeliveryNo, &task.PackageNo, &task.WaybillNo,
		&task.OrderPlaceType, &task.HandleResult, &task.PrintStatus, &task.Status, &task.FailureReason, &task.ResolutionStatus, &task.ResolutionReason, &task.ResolvedAt, &task.CreatedAt, &task.UpdatedAt,
		&task.OutboundOrderNo, &task.OutboundStatus, &task.OutboundStatusName, &task.LabelAttached,
		&task.OMSAccount, &task.OMSOrderNo, &task.OMSStatusCode, &task.OMSStatusKey, &task.OMSStatusText,
		&task.OMSWarehouseCode, &task.OMSSyncStatus, &task.OMSSyncMessage, &task.OMSQueriedAt,
	)
	if err != nil {
		return FulfillmentTask{}, fmt.Errorf("scan SHEIN fulfillment task: %w", err)
	}
	task.ParcelComplete = task.OutboundOrderNo != "" && task.LabelAttached &&
		task.OutboundStatus != nil && (*task.OutboundStatus == 0 || *task.OutboundStatus == 1 || *task.OutboundStatus == 2 || *task.OutboundStatus == 3)
	task.LabelPrintable = LabelPrintable(task)
	return task, nil
}

func scanFulfillmentTasks(rows pgx.Rows) ([]FulfillmentTask, error) {
	tasks := make([]FulfillmentTask, 0)
	for rows.Next() {
		task, err := scanFulfillmentTask(rows)
		if err != nil {
			return nil, err
		}
		tasks = append(tasks, task)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("list SHEIN fulfillment tasks: %w", err)
	}
	return tasks, nil
}

func (s *Store) OrderFulfillmentState(ctx context.Context, shopKey, orderNo string) (string, string, error) {
	orderNo = strings.TrimSpace(orderNo)
	if shopKey == "" || orderNo == "" {
		return "", "", nil
	}
	var status, normalized string
	err := s.pool.QueryRow(ctx, `
		SELECT COALESCE(order_status, ''), COALESCE(order_status_normalized, '')
		FROM shein_orders
		WHERE shop_key = $1 AND order_no = $2
	`, shopKey, orderNo).Scan(&status, &normalized)
	if errors.Is(err, pgx.ErrNoRows) {
		return "", "", nil
	}
	if err != nil {
		return "", "", fmt.Errorf("load SHEIN order fulfillment state: %w", err)
	}
	if strings.TrimSpace(normalized) == "" {
		normalized = NormalizeOrderStatus(status)
	}
	return status, normalized, nil
}

func (s *Store) OrderDetail(ctx context.Context, shopKey, orderNo string) (map[string]any, error) {
	orderNo = strings.TrimSpace(orderNo)
	if shopKey == "" || orderNo == "" {
		return nil, ErrOrderNotFound
	}
	var raw []byte
	err := s.pool.QueryRow(ctx, `
		SELECT detail_payload FROM shein_orders WHERE shop_key = $1 AND order_no = $2
	`, shopKey, orderNo).Scan(&raw)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrOrderNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("load SHEIN order detail: %w", err)
	}
	var detail map[string]any
	if err := json.Unmarshal(raw, &detail); err != nil {
		return nil, fmt.Errorf("decode SHEIN order detail: %w", err)
	}
	return detail, nil
}

func (s *Store) AttachOrderFulfillmentStates(ctx context.Context, shopKey string, tasks []FulfillmentTask) error {
	if len(tasks) == 0 {
		return nil
	}
	orderNos := make([]string, 0, len(tasks))
	seen := make(map[string]struct{}, len(tasks))
	for _, task := range tasks {
		orderNo := strings.TrimSpace(task.OrderNo)
		if orderNo == "" {
			continue
		}
		if _, exists := seen[orderNo]; exists {
			continue
		}
		seen[orderNo] = struct{}{}
		orderNos = append(orderNos, orderNo)
	}
	if len(orderNos) == 0 {
		return nil
	}
	rows, err := s.pool.Query(ctx, `
		SELECT order_no, COALESCE(order_status, ''), COALESCE(order_status_normalized, '')
		FROM shein_orders
		WHERE shop_key = $1 AND order_no = ANY($2)
	`, shopKey, orderNos)
	if err != nil {
		return fmt.Errorf("load SHEIN order fulfillment states: %w", err)
	}
	defer rows.Close()
	states := make(map[string][2]string, len(orderNos))
	for rows.Next() {
		var orderNo, status, normalized string
		if err := rows.Scan(&orderNo, &status, &normalized); err != nil {
			return fmt.Errorf("scan SHEIN order fulfillment state: %w", err)
		}
		if strings.TrimSpace(normalized) == "" {
			normalized = NormalizeOrderStatus(status)
		}
		states[orderNo] = [2]string{status, normalized}
	}
	if err := rows.Err(); err != nil {
		return err
	}
	for index := range tasks {
		if state, ok := states[tasks[index].OrderNo]; ok {
			tasks[index].OrderStatus = state[0]
			tasks[index].OrderStatusNormalized = state[1]
			tasks[index].LabelPrintable = LabelPrintable(tasks[index])
		}
	}
	return nil
}

func (s *Store) ListFulfillmentTasks(ctx context.Context, shopKey string, limit int) ([]FulfillmentTask, error) {
	if limit < 1 || limit > 500 {
		limit = 200
	}
	rows, err := s.pool.Query(ctx, fulfillmentTaskSelect+`
		WHERE shop_key = $1
		ORDER BY updated_at DESC
		LIMIT $2
	`, shopKey, limit)
	if err != nil {
		return nil, fmt.Errorf("list SHEIN fulfillment tasks: %w", err)
	}
	defer rows.Close()
	return scanFulfillmentTasks(rows)
}

func (s *Store) FailOperation(ctx context.Context, shopKey, operation, idempotencyKey, message string) error {
	if len(message) > 1000 {
		message = message[:1000]
	}
	_, err := s.pool.Exec(ctx, `
		UPDATE shein_go_api_operations
		SET status = 'failed', completed_at = now(), error_message = $4
		WHERE shop_key = $1 AND operation = $2 AND idempotency_key = $3
	`, shopKey, operation, idempotencyKey, message)
	if err != nil {
		return fmt.Errorf("fail SHEIN operation: %w", err)
	}
	return nil
}
