package shein

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

type Store struct {
	pool *pgxpool.Pool
}

type ShopSummary struct {
	ShopKey     string    `json:"shop_key"`
	APIBaseURL  string    `json:"api_base_url"`
	OpenKeyHint string    `json:"open_key_hint"`
	Credentials bool      `json:"credentials_ready"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type OperationRecord struct {
	Status       string
	RequestHash  string
	Response     map[string]any
	ErrorMessage string
}

type FulfillmentTask struct {
	OrderNo              string    `json:"order_no"`
	ExpressChannelCode   string    `json:"express_channel_code"`
	WarehouseAddressCode string    `json:"warehouse_address_code"`
	PlaceRequestID       string    `json:"place_request_id"`
	DeliveryNo           string    `json:"delivery_no"`
	PackageNo            string    `json:"package_no"`
	WaybillNo            string    `json:"waybill_no"`
	OrderPlaceType       *int      `json:"order_place_type,omitempty"`
	HandleResult         *int      `json:"handle_result,omitempty"`
	PrintStatus          *int      `json:"print_status,omitempty"`
	Status               string    `json:"status"`
	FailureReason        string    `json:"failure_reason,omitempty"`
	UpdatedAt            time.Time `json:"updated_at"`
}

func NewStore(ctx context.Context, databaseURL string) (*Store, error) {
	if strings.TrimSpace(databaseURL) == "" {
		return nil, errors.New("SHEIN_DATABASE_URL is required")
	}
	pool, err := pgxpool.New(ctx, databaseURL)
	if err != nil {
		return nil, fmt.Errorf("open SHEIN database: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping SHEIN database: %w", err)
	}
	return &Store{pool: pool}, nil
}

func (s *Store) Close() {
	s.pool.Close()
}

func (s *Store) Migrate(ctx context.Context) error {
	_, err := s.pool.Exec(ctx, `
		CREATE TABLE IF NOT EXISTS shein_go_api_operations (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			shop_key text NOT NULL,
			operation text NOT NULL,
			idempotency_key text NOT NULL,
			request_hash text NOT NULL,
			status text NOT NULL DEFAULT 'pending',
			response jsonb,
			error_message text,
			created_at timestamptz NOT NULL DEFAULT now(),
			completed_at timestamptz,
			UNIQUE (shop_key, operation, idempotency_key)
		);
		CREATE INDEX IF NOT EXISTS idx_shein_go_api_operations_created
			ON shein_go_api_operations (shop_key, created_at DESC);

		CREATE TABLE IF NOT EXISTS shein_go_fulfillment_tasks (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			shop_key text NOT NULL,
			order_no text NOT NULL,
			express_channel_code text NOT NULL DEFAULT '',
			warehouse_address_code text NOT NULL DEFAULT '',
			place_request_id text NOT NULL DEFAULT '',
			delivery_no text NOT NULL DEFAULT '',
			package_no text NOT NULL DEFAULT '',
			waybill_no text NOT NULL DEFAULT '',
			order_place_type integer,
			handle_result integer,
			print_status integer,
			status text NOT NULL DEFAULT 'discovered',
			failure_reason text NOT NULL DEFAULT '',
			created_at timestamptz NOT NULL DEFAULT now(),
			updated_at timestamptz NOT NULL DEFAULT now()
		);
		ALTER TABLE shein_go_fulfillment_tasks
			ADD COLUMN IF NOT EXISTS order_place_type integer;
		ALTER TABLE shein_go_fulfillment_tasks
			DROP CONSTRAINT IF EXISTS shein_go_fulfillment_tasks_check;
		ALTER TABLE shein_go_fulfillment_tasks
			DROP CONSTRAINT IF EXISTS shein_go_fulfillment_tasks_identifier_check;
		ALTER TABLE shein_go_fulfillment_tasks
			ADD CONSTRAINT shein_go_fulfillment_tasks_identifier_check
			CHECK (place_request_id <> '' OR delivery_no <> '' OR package_no <> '');
		CREATE UNIQUE INDEX IF NOT EXISTS idx_shein_go_fulfillment_tasks_place
			ON shein_go_fulfillment_tasks (shop_key, place_request_id) WHERE place_request_id <> '';
		CREATE UNIQUE INDEX IF NOT EXISTS idx_shein_go_fulfillment_tasks_delivery
			ON shein_go_fulfillment_tasks (shop_key, delivery_no) WHERE delivery_no <> '';
		CREATE UNIQUE INDEX IF NOT EXISTS idx_shein_go_fulfillment_tasks_package
			ON shein_go_fulfillment_tasks (shop_key, order_no, package_no) WHERE package_no <> '';
		CREATE INDEX IF NOT EXISTS idx_shein_go_fulfillment_tasks_updated
			ON shein_go_fulfillment_tasks (shop_key, updated_at DESC);

		CREATE TABLE IF NOT EXISTS shein_go_auto_fulfillment_jobs (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			shop_key text NOT NULL,
			order_no text NOT NULL,
			status text NOT NULL DEFAULT 'queued',
			current_step text NOT NULL DEFAULT 'queued',
			attempts integer NOT NULL DEFAULT 0,
			shein_sku text NOT NULL DEFAULT '',
			warehouse_sku text NOT NULL DEFAULT '',
			warehouse_address_code text NOT NULL DEFAULT '',
			pre_request_id text NOT NULL DEFAULT '',
			express_channel_code text NOT NULL DEFAULT '',
			performance_cost numeric(18,4),
			currency_code text NOT NULL DEFAULT '',
			place_request_id text NOT NULL DEFAULT '',
			delivery_no text NOT NULL DEFAULT '',
			error_code text NOT NULL DEFAULT '',
			error_message text NOT NULL DEFAULT '',
			created_at timestamptz NOT NULL DEFAULT now(),
			updated_at timestamptz NOT NULL DEFAULT now(),
			started_at timestamptz,
			completed_at timestamptz,
			UNIQUE (shop_key, order_no),
			CHECK (attempts >= 0),
			CHECK (performance_cost IS NULL OR performance_cost >= 0)
		);
		CREATE INDEX IF NOT EXISTS idx_shein_go_auto_jobs_queue
			ON shein_go_auto_fulfillment_jobs (shop_key, status, updated_at DESC);

		CREATE TABLE IF NOT EXISTS shein_go_bulk_fulfillment_batches (
			id text PRIMARY KEY,
			shop_key text NOT NULL,
			status text NOT NULL DEFAULT 'running',
			total_orders integer NOT NULL,
			succeeded_orders integer NOT NULL DEFAULT 0,
			failed_orders integer NOT NULL DEFAULT 0,
			failed_order_no text NOT NULL DEFAULT '',
			last_error text NOT NULL DEFAULT '',
			created_at timestamptz NOT NULL DEFAULT now(),
			updated_at timestamptz NOT NULL DEFAULT now(),
			completed_at timestamptz,
			CHECK (total_orders > 0),
			CHECK (succeeded_orders >= 0 AND failed_orders >= 0)
		);
		CREATE UNIQUE INDEX IF NOT EXISTS idx_shein_go_bulk_batches_running
			ON shein_go_bulk_fulfillment_batches (shop_key) WHERE status = 'running';
		CREATE INDEX IF NOT EXISTS idx_shein_go_bulk_batches_latest
			ON shein_go_bulk_fulfillment_batches (shop_key, created_at DESC);

		CREATE TABLE IF NOT EXISTS shein_go_bulk_fulfillment_items (
			batch_id text NOT NULL REFERENCES shein_go_bulk_fulfillment_batches(id) ON DELETE CASCADE,
			sequence_no integer NOT NULL,
			order_no text NOT NULL,
			status text NOT NULL DEFAULT 'pending',
			last_error text NOT NULL DEFAULT '',
			updated_at timestamptz NOT NULL DEFAULT now(),
			PRIMARY KEY (batch_id, order_no),
			UNIQUE (batch_id, sequence_no),
			CHECK (sequence_no > 0)
		);
		CREATE INDEX IF NOT EXISTS idx_shein_go_bulk_items_status
			ON shein_go_bulk_fulfillment_items (batch_id, status, sequence_no);

		CREATE TABLE IF NOT EXISTS shein_go_shipping_quotes (
			shop_key text NOT NULL,
			pre_request_id text NOT NULL,
			order_no text NOT NULL,
			warehouse_address_code text NOT NULL,
			quoted_at timestamptz NOT NULL DEFAULT now(),
			PRIMARY KEY (shop_key, pre_request_id)
		);
		CREATE TABLE IF NOT EXISTS shein_go_shipping_quote_candidates (
			shop_key text NOT NULL,
			pre_request_id text NOT NULL,
			express_channel_code text NOT NULL,
			express_id bigint,
			express_id_code text NOT NULL DEFAULT '',
			express_short_name text NOT NULL DEFAULT '',
			performance_cost numeric(18,4),
			currency_code text NOT NULL DEFAULT '',
			estimate_min_day integer,
			estimate_max_day integer,
			PRIMARY KEY (shop_key, pre_request_id, express_channel_code),
			FOREIGN KEY (shop_key, pre_request_id)
				REFERENCES shein_go_shipping_quotes (shop_key, pre_request_id) ON DELETE CASCADE,
			CHECK (performance_cost IS NULL OR performance_cost >= 0)
		);

		CREATE TABLE IF NOT EXISTS shein_label_purchase_choices (
			shop_key text NOT NULL,
			pre_request_id text NOT NULL,
			operation_idempotency_key text NOT NULL,
			order_no text NOT NULL,
			selection_source text NOT NULL,
			selected_price_rank smallint,
			selected_warehouse_address_code text NOT NULL,
			selected_express_id bigint,
			selected_express_id_code text NOT NULL DEFAULT '',
			selected_express_channel_code text NOT NULL,
			selected_express_short_name text NOT NULL DEFAULT '',
			selected_performance_cost numeric(18,4) NOT NULL,
			selected_currency_code text NOT NULL DEFAULT '',
			selected_estimate_min_day integer,
			selected_estimate_max_day integer,
			selection_reason text NOT NULL,
			place_request_id text NOT NULL DEFAULT '',
			delivery_no text NOT NULL DEFAULT '',
			purchased_at timestamptz NOT NULL DEFAULT now(),
			PRIMARY KEY (shop_key, pre_request_id),
			FOREIGN KEY (shop_key, pre_request_id)
				REFERENCES shein_go_shipping_quotes (shop_key, pre_request_id),
			CHECK (selection_source IN ('automatic', 'manual')),
			CHECK (selected_price_rank IS NULL OR selected_price_rank BETWEEN 1 AND 3),
			CHECK (selected_performance_cost >= 0)
		);
		CREATE INDEX IF NOT EXISTS idx_shein_label_purchase_choices_order
			ON shein_label_purchase_choices (shop_key, order_no, purchased_at DESC);
		CREATE INDEX IF NOT EXISTS idx_shein_label_purchase_choices_operation
			ON shein_label_purchase_choices (shop_key, operation_idempotency_key);

		CREATE TABLE IF NOT EXISTS shein_label_purchase_candidates (
			shop_key text NOT NULL,
			pre_request_id text NOT NULL,
			price_rank smallint NOT NULL,
			warehouse_address_code text NOT NULL,
			express_id bigint,
			express_id_code text NOT NULL DEFAULT '',
			express_channel_code text NOT NULL,
			express_short_name text NOT NULL DEFAULT '',
			performance_cost numeric(18,4) NOT NULL,
			currency_code text NOT NULL DEFAULT '',
			estimate_min_day integer,
			estimate_max_day integer,
			is_selected boolean NOT NULL DEFAULT false,
			PRIMARY KEY (shop_key, pre_request_id, price_rank),
			FOREIGN KEY (shop_key, pre_request_id)
				REFERENCES shein_label_purchase_choices (shop_key, pre_request_id) ON DELETE CASCADE,
			CHECK (price_rank BETWEEN 1 AND 3),
			CHECK (performance_cost >= 0)
		);
		CREATE INDEX IF NOT EXISTS idx_shein_label_purchase_candidates_price
			ON shein_label_purchase_candidates (shop_key, currency_code, performance_cost, price_rank);
	`)
	if err != nil {
		return fmt.Errorf("migrate SHEIN Go tables: %w", err)
	}
	return nil
}

func (s *Store) Credentials(ctx context.Context, shopKey string) (Credentials, error) {
	shopKey = strings.TrimSpace(shopKey)
	if shopKey == "" {
		shopKey = "default"
	}
	var credentials Credentials
	err := s.pool.QueryRow(ctx, `
		SELECT shop_key, open_key_id, secret_key, base_url
		FROM shein_shops
		WHERE shop_key = $1
	`, shopKey).Scan(&credentials.ShopKey, &credentials.OpenKeyID, &credentials.SecretKey, &credentials.BaseURL)
	if errors.Is(err, pgx.ErrNoRows) {
		return Credentials{}, fmt.Errorf("SHEIN shop %q is not configured", shopKey)
	}
	if err != nil {
		return Credentials{}, fmt.Errorf("load SHEIN shop credentials: %w", err)
	}
	if credentials.OpenKeyID == "" || credentials.SecretKey == "" {
		return Credentials{}, fmt.Errorf("SHEIN shop %q credentials are incomplete", shopKey)
	}
	return credentials, nil
}

func (s *Store) ListShops(ctx context.Context) ([]ShopSummary, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT shop_key, base_url, open_key_id, updated_at
		FROM shein_shops
		ORDER BY shop_key
	`)
	if err != nil {
		return nil, fmt.Errorf("list SHEIN shops: %w", err)
	}
	defer rows.Close()
	shops := make([]ShopSummary, 0)
	for rows.Next() {
		var shop ShopSummary
		var openKeyID string
		if err := rows.Scan(&shop.ShopKey, &shop.APIBaseURL, &openKeyID, &shop.UpdatedAt); err != nil {
			return nil, fmt.Errorf("scan SHEIN shop: %w", err)
		}
		shop.Credentials = openKeyID != ""
		shop.OpenKeyHint = credentialHint(openKeyID)
		shops = append(shops, shop)
	}
	return shops, rows.Err()
}

func credentialHint(value string) string {
	if len(value) <= 8 {
		return strings.Repeat("*", len(value))
	}
	return value[:4] + "..." + value[len(value)-4:]
}

func (s *Store) ReserveOperation(ctx context.Context, shopKey, operation, idempotencyKey, requestHash string) (OperationRecord, bool, error) {
	if len(idempotencyKey) < 8 || len(idempotencyKey) > 200 {
		return OperationRecord{}, false, errors.New("Idempotency-Key must contain between 8 and 200 characters")
	}
	tag, err := s.pool.Exec(ctx, `
		INSERT INTO shein_go_api_operations (shop_key, operation, idempotency_key, request_hash)
		VALUES ($1, $2, $3, $4)
		ON CONFLICT DO NOTHING
	`, shopKey, operation, idempotencyKey, requestHash)
	if err != nil {
		return OperationRecord{}, false, fmt.Errorf("reserve SHEIN operation: %w", err)
	}
	if tag.RowsAffected() == 1 {
		return OperationRecord{Status: "pending", RequestHash: requestHash}, true, nil
	}
	var record OperationRecord
	var responseJSON []byte
	err = s.pool.QueryRow(ctx, `
		SELECT status, request_hash, COALESCE(response, '{}'::jsonb), COALESCE(error_message, '')
		FROM shein_go_api_operations
		WHERE shop_key = $1 AND operation = $2 AND idempotency_key = $3
	`, shopKey, operation, idempotencyKey).Scan(&record.Status, &record.RequestHash, &responseJSON, &record.ErrorMessage)
	if err != nil {
		return OperationRecord{}, false, fmt.Errorf("load reserved SHEIN operation: %w", err)
	}
	if record.RequestHash != requestHash {
		return OperationRecord{}, false, errors.New("Idempotency-Key was already used with a different request")
	}
	if len(responseJSON) > 0 {
		_ = json.Unmarshal(responseJSON, &record.Response)
	}
	return record, false, nil
}

func (s *Store) CompleteOperation(ctx context.Context, shopKey, operation, idempotencyKey string, response map[string]any) error {
	encoded, err := json.Marshal(response)
	if err != nil {
		return fmt.Errorf("encode SHEIN operation response: %w", err)
	}
	_, err = s.pool.Exec(ctx, `
		UPDATE shein_go_api_operations
		SET status = 'completed', response = $4::jsonb, completed_at = now(), error_message = NULL
		WHERE shop_key = $1 AND operation = $2 AND idempotency_key = $3
	`, shopKey, operation, idempotencyKey, encoded)
	if err != nil {
		return fmt.Errorf("complete SHEIN operation: %w", err)
	}
	return nil
}

func (s *Store) UpsertFulfillmentTask(ctx context.Context, shopKey string, task FulfillmentTask) error {
	shopKey = strings.TrimSpace(shopKey)
	task.OrderNo = strings.TrimSpace(task.OrderNo)
	task.PlaceRequestID = strings.TrimSpace(task.PlaceRequestID)
	task.DeliveryNo = strings.TrimSpace(task.DeliveryNo)
	task.PackageNo = strings.TrimSpace(task.PackageNo)
	if shopKey == "" || task.OrderNo == "" || task.PlaceRequestID == "" && task.DeliveryNo == "" && task.PackageNo == "" {
		return errors.New("shop, order and a fulfillment identifier are required for a fulfillment task")
	}
	if task.Status == "" {
		task.Status = "discovered"
	}
	query := `
		WITH updated AS (
			UPDATE shein_go_fulfillment_tasks
			SET order_no = $2,
				express_channel_code = COALESCE(NULLIF($3, ''), express_channel_code),
				warehouse_address_code = COALESCE(NULLIF($4, ''), warehouse_address_code),
				place_request_id = COALESCE(NULLIF($5, ''), place_request_id),
				delivery_no = COALESCE(NULLIF($6, ''), delivery_no),
				package_no = COALESCE(NULLIF($7, ''), package_no),
				waybill_no = COALESCE(NULLIF($8, ''), waybill_no),
				order_place_type = COALESCE($9, order_place_type),
				handle_result = COALESCE($10, handle_result),
				print_status = COALESCE($11, print_status),
				status = COALESCE(NULLIF($12, ''), status),
				failure_reason = $13,
				updated_at = now()
			WHERE shop_key = $1 AND (
				($5 <> '' AND place_request_id = $5)
				OR ($6 <> '' AND delivery_no = $6)
				OR ($7 <> '' AND order_no = $2 AND package_no = $7)
			)
			RETURNING id
		)
		INSERT INTO shein_go_fulfillment_tasks (
			shop_key, order_no, express_channel_code, warehouse_address_code,
			place_request_id, delivery_no, package_no, waybill_no,
			order_place_type, handle_result, print_status, status, failure_reason
		)
		SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
		WHERE NOT EXISTS (SELECT 1 FROM updated)
		ON CONFLICT DO NOTHING
	`
	if _, err := s.pool.Exec(ctx, query,
		shopKey, task.OrderNo, task.ExpressChannelCode, task.WarehouseAddressCode,
		task.PlaceRequestID, task.DeliveryNo, task.PackageNo, task.WaybillNo,
		task.OrderPlaceType, task.HandleResult, task.PrintStatus, task.Status, task.FailureReason,
	); err != nil {
		return fmt.Errorf("upsert SHEIN fulfillment task: %w", err)
	}
	return nil
}

func (s *Store) UpdateFulfillmentTaskResult(
	ctx context.Context,
	shopKey, placeRequestID, deliveryNo, expressChannelCode, warehouseAddressCode, status, failureReason string,
	handleResult, printStatus *int,
) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE shein_go_fulfillment_tasks
		SET place_request_id = COALESCE(NULLIF($2, ''), place_request_id),
			delivery_no = COALESCE(NULLIF($3, ''), delivery_no),
			express_channel_code = COALESCE(NULLIF($4, ''), express_channel_code),
			warehouse_address_code = COALESCE(NULLIF($5, ''), warehouse_address_code),
			handle_result = COALESCE($6, handle_result),
			print_status = COALESCE($7, print_status),
			status = COALESCE(NULLIF($8, ''), status),
			failure_reason = $9,
			updated_at = now()
		WHERE shop_key = $1
			AND (($2 <> '' AND place_request_id = $2) OR ($3 <> '' AND delivery_no = $3))
	`, shopKey, placeRequestID, deliveryNo, expressChannelCode, warehouseAddressCode,
		handleResult, printStatus, status, failureReason)
	if err != nil {
		return fmt.Errorf("update SHEIN fulfillment task result: %w", err)
	}
	return nil
}

func (s *Store) MarkFulfillmentTaskLabelReady(
	ctx context.Context,
	shopKey, deliveryNo, orderNo string,
	packageNos []string,
) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE shein_go_fulfillment_tasks
		SET status = 'label_ready', print_status = 2, updated_at = now()
		WHERE shop_key = $1 AND (
			($2 <> '' AND delivery_no = $2)
			OR ($3 <> '' AND order_no = $3 AND package_no = ANY($4::text[]))
		)
	`, shopKey, deliveryNo, orderNo, packageNos)
	if err != nil {
		return fmt.Errorf("mark SHEIN fulfillment task label ready: %w", err)
	}
	return nil
}

func (s *Store) ListFulfillmentTasks(ctx context.Context, shopKey string, limit int) ([]FulfillmentTask, error) {
	if limit < 1 || limit > 500 {
		limit = 200
	}
	rows, err := s.pool.Query(ctx, `
		SELECT order_no, express_channel_code, warehouse_address_code,
			place_request_id, delivery_no, package_no, waybill_no,
			order_place_type, handle_result, print_status, status, failure_reason, updated_at
		FROM shein_go_fulfillment_tasks
		WHERE shop_key = $1
		ORDER BY updated_at DESC
		LIMIT $2
	`, shopKey, limit)
	if err != nil {
		return nil, fmt.Errorf("list SHEIN fulfillment tasks: %w", err)
	}
	defer rows.Close()
	tasks := make([]FulfillmentTask, 0)
	for rows.Next() {
		var task FulfillmentTask
		if err := rows.Scan(
			&task.OrderNo, &task.ExpressChannelCode, &task.WarehouseAddressCode,
			&task.PlaceRequestID, &task.DeliveryNo, &task.PackageNo, &task.WaybillNo,
			&task.OrderPlaceType, &task.HandleResult, &task.PrintStatus, &task.Status, &task.FailureReason, &task.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("scan SHEIN fulfillment task: %w", err)
		}
		tasks = append(tasks, task)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("list SHEIN fulfillment tasks: %w", err)
	}
	return tasks, nil
}

func (s *Store) FailOperation(ctx context.Context, shopKey, operation, idempotencyKey, message string) error {
	if len(message) > 1000 {
		message = message[:1000]
	}
	_, err := s.pool.Exec(ctx, `
		UPDATE shein_go_api_operations
		SET status = 'failed', completed_at = now(), error_message = $4
		WHERE shop_key = $1 AND operation = $2 AND idempotency_key = $3
	`, shopKey, operation, idempotencyKey, message)
	if err != nil {
		return fmt.Errorf("fail SHEIN operation: %w", err)
	}
	return nil
}
