from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
import re
from typing import Any

import psycopg
from psycopg import sql
from psycopg.conninfo import make_conninfo
from psycopg.types.json import Jsonb

from .client import StoreCredentials


SHOP_CODE_PATTERN = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
SCHEMA_NAME_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")


REGISTRY_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS public.shein_shops (
    shop_key text PRIMARY KEY,
    shop_name text,
    schema_name text,
    app_id text,
    open_key_id text NOT NULL,
    secret_key text NOT NULL,
    base_url text NOT NULL,
    state text,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.shein_shops ADD COLUMN IF NOT EXISTS shop_name text;
ALTER TABLE public.shein_shops ADD COLUMN IF NOT EXISTS schema_name text;
ALTER TABLE public.shein_shops ADD COLUMN IF NOT EXISTS enabled boolean NOT NULL DEFAULT true;

UPDATE public.shein_shops
SET shop_name = COALESCE(NULLIF(BTRIM(shop_name), ''), shop_key),
    schema_name = COALESCE(
        NULLIF(BTRIM(schema_name), ''),
        'shein_' || TRIM(BOTH '_' FROM regexp_replace(lower(shop_key), '[^a-z0-9]+', '_', 'g'))
    )
WHERE NULLIF(BTRIM(shop_name), '') IS NULL OR NULLIF(BTRIM(schema_name), '') IS NULL;

ALTER TABLE public.shein_shops ALTER COLUMN shop_name SET NOT NULL;
ALTER TABLE public.shein_shops ALTER COLUMN schema_name SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_shein_shops_schema_name
    ON public.shein_shops (schema_name);
"""


SHOP_SCHEMA_SQL = """

CREATE TABLE IF NOT EXISTS shein_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL REFERENCES public.shein_shops(shop_key) ON UPDATE CASCADE ON DELETE CASCADE,
    order_no text NOT NULL,
    order_status text,
    order_status_label text,
    order_status_normalized text NOT NULL DEFAULT 'unknown',
    order_type text,
    order_type_label text,
    order_created_at text,
    order_updated_at text,
    return_detected boolean NOT NULL DEFAULT false,
    return_status text NOT NULL DEFAULT 'none',
    order_return_time text,
    return_evidence jsonb NOT NULL DEFAULT '[]'::jsonb,
    list_payload jsonb NOT NULL,
    detail_payload jsonb,
    detail_fetched_at timestamptz,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shop_key, order_no)
);

ALTER TABLE shein_orders
    ADD COLUMN IF NOT EXISTS order_status_label text,
    ADD COLUMN IF NOT EXISTS order_status_normalized text NOT NULL DEFAULT 'unknown',
    ADD COLUMN IF NOT EXISTS order_type text,
    ADD COLUMN IF NOT EXISTS order_type_label text,
    ADD COLUMN IF NOT EXISTS return_detected boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS return_status text NOT NULL DEFAULT 'none',
    ADD COLUMN IF NOT EXISTS order_return_time text,
    ADD COLUMN IF NOT EXISTS return_evidence jsonb NOT NULL DEFAULT '[]'::jsonb;

CREATE INDEX IF NOT EXISTS idx_shein_orders_shop_last_seen
    ON shein_orders (shop_key, last_seen_at DESC);

CREATE INDEX IF NOT EXISTS idx_shein_orders_shop_return
    ON shein_orders (shop_key, return_detected, order_return_time);

CREATE INDEX IF NOT EXISTS idx_shein_orders_shop_status_normalized
    ON shein_orders (shop_key, order_status_normalized);

CREATE INDEX IF NOT EXISTS idx_shein_orders_shop_order_type
    ON shein_orders (shop_key, order_type);


CREATE TABLE IF NOT EXISTS shein_return_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL REFERENCES public.shein_shops(shop_key) ON UPDATE CASCADE ON DELETE CASCADE,
    return_plan_no text NOT NULL,
    status text,
    status_label text,
    return_reason_type text,
    return_reason_label text,
    return_deal_type text,
    return_deal_label text,
    initiator text,
    initiator_label text,
    return_time text,
    update_time text,
    related_orders jsonb NOT NULL DEFAULT '{}'::jsonb,
    return_order_nos jsonb NOT NULL DEFAULT '[]'::jsonb,
    raw_payload jsonb NOT NULL,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shop_key, return_plan_no)
);

CREATE INDEX IF NOT EXISTS idx_shein_return_applications_shop_status
    ON shein_return_applications (shop_key, status);

CREATE INDEX IF NOT EXISTS idx_shein_return_applications_shop_return_time
    ON shein_return_applications (shop_key, return_time);

CREATE TABLE IF NOT EXISTS shein_order_returns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL REFERENCES public.shein_shops(shop_key) ON UPDATE CASCADE ON DELETE CASCADE,
    return_no text NOT NULL,
    order_no text,
    return_status text,
    return_status_label text,
    no_return_goods_sign text,
    return_order_tag_code text,
    site text,
    platform_express_no text,
    member_express_no text,
    express_company_name text,
    performance_cost numeric,
    invoice_status text,
    request_return_time text,
    allocate_time text,
    last_update_time text,
    seller_signed_time text,
    cancel_time text,
    completed_time text,
    check_status text,
    stock_mode text,
    receive_type text,
    refund_order_nos jsonb NOT NULL DEFAULT '[]'::jsonb,
    return_goods_info_list jsonb NOT NULL DEFAULT '[]'::jsonb,
    raw_payload jsonb NOT NULL,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shop_key, return_no)
);

ALTER TABLE shein_order_returns
    ADD COLUMN IF NOT EXISTS no_return_goods_sign text,
    ADD COLUMN IF NOT EXISTS return_order_tag_code text,
    ADD COLUMN IF NOT EXISTS site text,
    ADD COLUMN IF NOT EXISTS platform_express_no text,
    ADD COLUMN IF NOT EXISTS member_express_no text,
    ADD COLUMN IF NOT EXISTS express_company_name text,
    ADD COLUMN IF NOT EXISTS performance_cost numeric,
    ADD COLUMN IF NOT EXISTS invoice_status text,
    ADD COLUMN IF NOT EXISTS request_return_time text,
    ADD COLUMN IF NOT EXISTS allocate_time text,
    ADD COLUMN IF NOT EXISTS last_update_time text,
    ADD COLUMN IF NOT EXISTS seller_signed_time text,
    ADD COLUMN IF NOT EXISTS cancel_time text,
    ADD COLUMN IF NOT EXISTS completed_time text,
    ADD COLUMN IF NOT EXISTS check_status text,
    ADD COLUMN IF NOT EXISTS stock_mode text,
    ADD COLUMN IF NOT EXISTS receive_type text,
    ADD COLUMN IF NOT EXISTS refund_order_nos jsonb NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS return_goods_info_list jsonb NOT NULL DEFAULT '[]'::jsonb;

CREATE INDEX IF NOT EXISTS idx_shein_order_returns_shop_order
    ON shein_order_returns (shop_key, order_no);

CREATE INDEX IF NOT EXISTS idx_shein_order_returns_shop_status
    ON shein_order_returns (shop_key, return_status);

CREATE INDEX IF NOT EXISTS idx_shein_order_returns_shop_request_time
    ON shein_order_returns (shop_key, request_return_time);

CREATE TABLE IF NOT EXISTS shein_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL,
    spu_name text,
    skc_name text NOT NULL,
    sku_code_list jsonb NOT NULL DEFAULT '[]'::jsonb,
    raw_payload jsonb NOT NULL,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shop_key, skc_name)
);

ALTER TABLE shein_products
    ADD COLUMN IF NOT EXISTS spu_name text,
    ADD COLUMN IF NOT EXISTS sku_code_list jsonb NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS first_seen_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS last_seen_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_shein_products_shop_spu
    ON shein_products (shop_key, spu_name);

CREATE INDEX IF NOT EXISTS idx_shein_products_shop_last_seen
    ON shein_products (shop_key, last_seen_at DESC);

CREATE INDEX IF NOT EXISTS idx_shein_products_sku_code_list
    ON shein_products USING gin (sku_code_list);

CREATE TABLE IF NOT EXISTS shein_product_details (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL,
    spu_name text NOT NULL,
    spu_shelf_status integer,
    category_id text,
    skc_list jsonb NOT NULL DEFAULT '[]'::jsonb,
    raw_payload jsonb NOT NULL,
    detail_fetched_at timestamptz NOT NULL DEFAULT now(),
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shop_key, spu_name)
);

ALTER TABLE shein_product_details
    ADD COLUMN IF NOT EXISTS spu_shelf_status integer,
    ADD COLUMN IF NOT EXISTS category_id text,
    ADD COLUMN IF NOT EXISTS skc_list jsonb NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS detail_fetched_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS first_seen_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS last_seen_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_shein_product_details_shop_status
    ON shein_product_details (shop_key, spu_shelf_status);

CREATE INDEX IF NOT EXISTS idx_shein_product_details_shop_category
    ON shein_product_details (shop_key, category_id);

CREATE INDEX IF NOT EXISTS idx_shein_product_details_shop_last_seen
    ON shein_product_details (shop_key, last_seen_at DESC);

CREATE TABLE IF NOT EXISTS shein_sync_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    status text NOT NULL,
    query_params jsonb NOT NULL,
    pages integer NOT NULL DEFAULT 0,
    orders_seen integer NOT NULL DEFAULT 0,
    orders_upserted integer NOT NULL DEFAULT 0,
    error text
);

CREATE TABLE IF NOT EXISTS shein_order_full_sync_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL REFERENCES public.shein_shops(shop_key) ON UPDATE CASCADE ON DELETE CASCADE,
    sync_key text NOT NULL,
    query_type integer NOT NULL,
    start_time text NOT NULL,
    end_time text NOT NULL,
    base_params jsonb NOT NULL,
    window_hours numeric NOT NULL,
    list_rps numeric NOT NULL,
    detail_rps numeric NOT NULL,
    status text NOT NULL,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    last_error text,
    UNIQUE (shop_key, sync_key)
);

CREATE TABLE IF NOT EXISTS shein_order_full_sync_windows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id bigint NOT NULL REFERENCES shein_order_full_sync_jobs(id) ON DELETE CASCADE,
    window_index integer NOT NULL,
    start_time text NOT NULL,
    end_time text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    next_page integer NOT NULL DEFAULT 1,
    pages integer NOT NULL DEFAULT 0,
    orders_seen integer NOT NULL DEFAULT 0,
    orders_upserted integer NOT NULL DEFAULT 0,
    details_fetched integer NOT NULL DEFAULT 0,
    detail_batches integer NOT NULL DEFAULT 0,
    started_at timestamptz,
    finished_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    last_error text,
    UNIQUE (job_id, window_index)
);

CREATE INDEX IF NOT EXISTS idx_shein_order_full_sync_windows_job_status
    ON shein_order_full_sync_windows (job_id, status, window_index);

CREATE TABLE IF NOT EXISTS shein_sku_mappings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL,
    warehouse_sku text NOT NULL,
    shein_sku text NOT NULL,
    sku_group text NOT NULL DEFAULT 'default',
    warehouse_qty numeric NOT NULL DEFAULT 1,
    length_cm numeric,
    width_cm numeric,
    height_cm numeric,
    weight_kg numeric,
    cost_price numeric,
    purchase_price numeric,
    ocean_freight_price numeric,
    note text,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shop_key, warehouse_sku, shein_sku)
);

ALTER TABLE shein_sku_mappings
    ADD COLUMN IF NOT EXISTS sku_group text NOT NULL DEFAULT 'default',
    ADD COLUMN IF NOT EXISTS warehouse_qty numeric NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS length_cm numeric,
    ADD COLUMN IF NOT EXISTS width_cm numeric,
    ADD COLUMN IF NOT EXISTS height_cm numeric,
    ADD COLUMN IF NOT EXISTS weight_kg numeric,
    ADD COLUMN IF NOT EXISTS cost_price numeric,
    ADD COLUMN IF NOT EXISTS purchase_price numeric,
    ADD COLUMN IF NOT EXISTS ocean_freight_price numeric,
    ADD COLUMN IF NOT EXISTS note text,
    ADD COLUMN IF NOT EXISTS enabled boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_shein_sku_mappings_shop_warehouse
    ON shein_sku_mappings (shop_key, warehouse_sku);

CREATE INDEX IF NOT EXISTS idx_shein_sku_mappings_shop_shein
    ON shein_sku_mappings (shop_key, shein_sku);

CREATE TABLE IF NOT EXISTS shein_sku_mapping_settings (
    shop_key text PRIMARY KEY,
    default_warehouse_sku text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS shein_warehouse_skus (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL,
    warehouse_sku text NOT NULL,
    length_cm numeric,
    width_cm numeric,
    height_cm numeric,
    weight_kg numeric,
    cost_price numeric,
    purchase_price numeric,
    ocean_freight_price numeric,
    operation_fee_price numeric NOT NULL DEFAULT 0,
    note text,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shop_key, warehouse_sku)
);

ALTER TABLE shein_warehouse_skus
    ADD COLUMN IF NOT EXISTS length_cm numeric,
    ADD COLUMN IF NOT EXISTS width_cm numeric,
    ADD COLUMN IF NOT EXISTS height_cm numeric,
    ADD COLUMN IF NOT EXISTS weight_kg numeric,
    ADD COLUMN IF NOT EXISTS cost_price numeric,
    ADD COLUMN IF NOT EXISTS purchase_price numeric,
    ADD COLUMN IF NOT EXISTS ocean_freight_price numeric,
    ADD COLUMN IF NOT EXISTS operation_fee_price numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS note text,
    ADD COLUMN IF NOT EXISTS enabled boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

INSERT INTO shein_warehouse_skus (shop_key, warehouse_sku)
SELECT DISTINCT shop_key, warehouse_sku
FROM shein_sku_mappings
WHERE NULLIF(BTRIM(warehouse_sku), '') IS NOT NULL
ON CONFLICT (shop_key, warehouse_sku) DO NOTHING;

WITH mapping_rollup AS (
    SELECT
        shop_key,
        warehouse_sku,
        MAX(length_cm) FILTER (WHERE length_cm IS NOT NULL) AS length_cm,
        MAX(width_cm) FILTER (WHERE width_cm IS NOT NULL) AS width_cm,
        MAX(height_cm) FILTER (WHERE height_cm IS NOT NULL) AS height_cm,
        MAX(weight_kg) FILTER (WHERE weight_kg IS NOT NULL) AS weight_kg,
        MAX(cost_price) FILTER (WHERE cost_price IS NOT NULL) AS cost_price,
        MAX(purchase_price) FILTER (WHERE purchase_price IS NOT NULL) AS purchase_price,
        MAX(ocean_freight_price) FILTER (WHERE ocean_freight_price IS NOT NULL) AS ocean_freight_price
    FROM shein_sku_mappings
    WHERE NULLIF(BTRIM(warehouse_sku), '') IS NOT NULL
    GROUP BY shop_key, warehouse_sku
)
UPDATE shein_warehouse_skus w
SET length_cm = COALESCE(w.length_cm, r.length_cm),
    width_cm = COALESCE(w.width_cm, r.width_cm),
    height_cm = COALESCE(w.height_cm, r.height_cm),
    weight_kg = COALESCE(w.weight_kg, r.weight_kg),
    cost_price = COALESCE(w.cost_price, r.cost_price),
    purchase_price = COALESCE(w.purchase_price, r.purchase_price),
    ocean_freight_price = COALESCE(w.ocean_freight_price, r.ocean_freight_price)
FROM mapping_rollup r
WHERE w.shop_key = r.shop_key AND w.warehouse_sku = r.warehouse_sku;

CREATE INDEX IF NOT EXISTS idx_shein_warehouse_skus_shop_enabled
    ON shein_warehouse_skus (shop_key, enabled, warehouse_sku);
"""


@dataclass(frozen=True)
class OrderFullSyncWindow:
    id: int
    window_index: int
    start_time: str
    end_time: str
    status: str
    next_page: int


def connect(database_url: str) -> psycopg.Connection:
    return psycopg.connect(database_url)


def schema_database_url(database_url: str, schema_name: str) -> str:
    schema_name = schema_name.strip()
    if not SCHEMA_NAME_PATTERN.fullmatch(schema_name):
        raise ValueError("invalid PostgreSQL shop schema")
    return make_conninfo(database_url, options=f"-csearch_path={schema_name},public")


@lru_cache(maxsize=32)
def shop_database_url(database_url: str, shop_key: str) -> str:
    shop_key = shop_key.strip()
    if not SHOP_CODE_PATTERN.fullmatch(shop_key):
        raise ValueError("invalid SHEIN shop code")
    with psycopg.connect(database_url) as conn:
        row = conn.execute(
            """
            SELECT schema_name
            FROM public.shein_shops
            WHERE shop_key = %s AND enabled = true
            """,
            (shop_key,),
        ).fetchone()
    if not row:
        raise KeyError(f"shop_key not found or disabled in public.shein_shops: {shop_key}")
    return schema_database_url(database_url, str(row[0]))


def list_registered_shops(database_url: str, *, enabled_only: bool = False) -> list[dict[str, Any]]:
    query = """
        SELECT shop_key, shop_name, schema_name, enabled, created_at, updated_at
        FROM public.shein_shops
    """
    if enabled_only:
        query += " WHERE enabled = true"
    query += " ORDER BY shop_name, shop_key"
    with psycopg.connect(database_url) as conn:
        rows = conn.execute(query).fetchall()
    return [
        {
            "shop_key": row[0],
            "shop_name": row[1],
            "schema_name": row[2],
            "enabled": bool(row[3]),
            "created_at": row[4],
            "updated_at": row[5],
        }
        for row in rows
    ]


def init_registry(database_url: str) -> None:
    with psycopg.connect(database_url) as conn:
        conn.execute(REGISTRY_SCHEMA_SQL)
    shop_database_url.cache_clear()


def init_shop_schema(database_url: str, shop_key: str) -> None:
    target_url = shop_database_url(database_url, shop_key)
    with connect(target_url) as conn:
        conn.execute(SHOP_SCHEMA_SQL)
        conn.execute(INVENTORY_SCHEMA_SQL)


def init_db(database_url: str, *, shop_key: str | None = None) -> None:
    init_registry(database_url)
    shops = list_registered_shops(database_url, enabled_only=True)
    if shop_key is not None:
        shops = [shop for shop in shops if shop["shop_key"] == shop_key]
        if not shops:
            raise KeyError(f"shop_key not found or disabled in public.shein_shops: {shop_key}")
    with psycopg.connect(database_url) as conn:
        for shop in shops:
            schema_name = str(shop["schema_name"])
            if not SCHEMA_NAME_PATTERN.fullmatch(schema_name):
                raise ValueError(f"invalid PostgreSQL schema for shop {shop['shop_key']}")
            conn.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(schema_name)))
    for shop in shops:
        init_shop_schema(database_url, str(shop["shop_key"]))


SKU_MAPPING_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS shein_sku_mappings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL,
    warehouse_sku text NOT NULL,
    shein_sku text NOT NULL,
    sku_group text NOT NULL DEFAULT 'default',
    warehouse_qty numeric NOT NULL DEFAULT 1,
    length_cm numeric,
    width_cm numeric,
    height_cm numeric,
    weight_kg numeric,
    cost_price numeric,
    purchase_price numeric,
    ocean_freight_price numeric,
    note text,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shop_key, warehouse_sku, shein_sku)
);

ALTER TABLE shein_sku_mappings
    ADD COLUMN IF NOT EXISTS sku_group text NOT NULL DEFAULT 'default',
    ADD COLUMN IF NOT EXISTS warehouse_qty numeric NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS length_cm numeric,
    ADD COLUMN IF NOT EXISTS width_cm numeric,
    ADD COLUMN IF NOT EXISTS height_cm numeric,
    ADD COLUMN IF NOT EXISTS weight_kg numeric,
    ADD COLUMN IF NOT EXISTS cost_price numeric,
    ADD COLUMN IF NOT EXISTS purchase_price numeric,
    ADD COLUMN IF NOT EXISTS ocean_freight_price numeric,
    ADD COLUMN IF NOT EXISTS note text,
    ADD COLUMN IF NOT EXISTS enabled boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_shein_sku_mappings_shop_warehouse
    ON shein_sku_mappings (shop_key, warehouse_sku);

CREATE INDEX IF NOT EXISTS idx_shein_sku_mappings_shop_shein
    ON shein_sku_mappings (shop_key, shein_sku);

CREATE TABLE IF NOT EXISTS shein_sku_mapping_settings (
    shop_key text PRIMARY KEY,
    default_warehouse_sku text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS shein_warehouse_skus (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL,
    warehouse_sku text NOT NULL,
    length_cm numeric,
    width_cm numeric,
    height_cm numeric,
    weight_kg numeric,
    cost_price numeric,
    purchase_price numeric,
    ocean_freight_price numeric,
    operation_fee_price numeric NOT NULL DEFAULT 0,
    note text,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shop_key, warehouse_sku)
);

ALTER TABLE shein_warehouse_skus
    ADD COLUMN IF NOT EXISTS length_cm numeric,
    ADD COLUMN IF NOT EXISTS width_cm numeric,
    ADD COLUMN IF NOT EXISTS height_cm numeric,
    ADD COLUMN IF NOT EXISTS weight_kg numeric,
    ADD COLUMN IF NOT EXISTS cost_price numeric,
    ADD COLUMN IF NOT EXISTS purchase_price numeric,
    ADD COLUMN IF NOT EXISTS ocean_freight_price numeric,
    ADD COLUMN IF NOT EXISTS operation_fee_price numeric NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS note text,
    ADD COLUMN IF NOT EXISTS enabled boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

INSERT INTO shein_warehouse_skus (shop_key, warehouse_sku)
SELECT DISTINCT shop_key, warehouse_sku
FROM shein_sku_mappings
WHERE NULLIF(BTRIM(warehouse_sku), '') IS NOT NULL
ON CONFLICT (shop_key, warehouse_sku) DO NOTHING;

WITH mapping_rollup AS (
    SELECT
        shop_key,
        warehouse_sku,
        MAX(length_cm) FILTER (WHERE length_cm IS NOT NULL) AS length_cm,
        MAX(width_cm) FILTER (WHERE width_cm IS NOT NULL) AS width_cm,
        MAX(height_cm) FILTER (WHERE height_cm IS NOT NULL) AS height_cm,
        MAX(weight_kg) FILTER (WHERE weight_kg IS NOT NULL) AS weight_kg,
        MAX(cost_price) FILTER (WHERE cost_price IS NOT NULL) AS cost_price,
        MAX(purchase_price) FILTER (WHERE purchase_price IS NOT NULL) AS purchase_price,
        MAX(ocean_freight_price) FILTER (WHERE ocean_freight_price IS NOT NULL) AS ocean_freight_price
    FROM shein_sku_mappings
    WHERE NULLIF(BTRIM(warehouse_sku), '') IS NOT NULL
    GROUP BY shop_key, warehouse_sku
)
UPDATE shein_warehouse_skus w
SET length_cm = COALESCE(w.length_cm, r.length_cm),
    width_cm = COALESCE(w.width_cm, r.width_cm),
    height_cm = COALESCE(w.height_cm, r.height_cm),
    weight_kg = COALESCE(w.weight_kg, r.weight_kg),
    cost_price = COALESCE(w.cost_price, r.cost_price),
    purchase_price = COALESCE(w.purchase_price, r.purchase_price),
    ocean_freight_price = COALESCE(w.ocean_freight_price, r.ocean_freight_price)
FROM mapping_rollup r
WHERE w.shop_key = r.shop_key AND w.warehouse_sku = r.warehouse_sku;

CREATE INDEX IF NOT EXISTS idx_shein_warehouse_skus_shop_enabled
    ON shein_warehouse_skus (shop_key, enabled, warehouse_sku);
"""


PRODUCT_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS shein_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL,
    spu_name text,
    skc_name text NOT NULL,
    sku_code_list jsonb NOT NULL DEFAULT '[]'::jsonb,
    raw_payload jsonb NOT NULL,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shop_key, skc_name)
);

ALTER TABLE shein_products
    ADD COLUMN IF NOT EXISTS spu_name text,
    ADD COLUMN IF NOT EXISTS sku_code_list jsonb NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS first_seen_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS last_seen_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_shein_products_shop_spu
    ON shein_products (shop_key, spu_name);

CREATE INDEX IF NOT EXISTS idx_shein_products_shop_last_seen
    ON shein_products (shop_key, last_seen_at DESC);

CREATE INDEX IF NOT EXISTS idx_shein_products_sku_code_list
    ON shein_products USING gin (sku_code_list);

CREATE TABLE IF NOT EXISTS shein_product_details (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL,
    spu_name text NOT NULL,
    spu_shelf_status integer,
    category_id text,
    skc_list jsonb NOT NULL DEFAULT '[]'::jsonb,
    raw_payload jsonb NOT NULL,
    detail_fetched_at timestamptz NOT NULL DEFAULT now(),
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shop_key, spu_name)
);

ALTER TABLE shein_product_details
    ADD COLUMN IF NOT EXISTS spu_shelf_status integer,
    ADD COLUMN IF NOT EXISTS category_id text,
    ADD COLUMN IF NOT EXISTS skc_list jsonb NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS detail_fetched_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS first_seen_at timestamptz NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS last_seen_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_shein_product_details_shop_status
    ON shein_product_details (shop_key, spu_shelf_status);

CREATE INDEX IF NOT EXISTS idx_shein_product_details_shop_category
    ON shein_product_details (shop_key, category_id);

CREATE INDEX IF NOT EXISTS idx_shein_product_details_shop_last_seen
    ON shein_product_details (shop_key, last_seen_at DESC);
"""


def ensure_sku_mapping_schema(database_url: str) -> None:
    with connect(database_url) as conn:
        conn.execute(SKU_MAPPING_SCHEMA_SQL)


def ensure_product_schema(database_url: str) -> None:
    with connect(database_url) as conn:
        conn.execute(PRODUCT_SCHEMA_SQL)


INVENTORY_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS inventory_schema_migrations (
    migration_key text PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS inventory_cost_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL,
    name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shop_key, name)
);

CREATE INDEX IF NOT EXISTS idx_inventory_cost_templates_shop
    ON inventory_cost_templates (shop_key, updated_at DESC, id);

CREATE TABLE IF NOT EXISTS inventory_tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL,
    ticket_no text NOT NULL,
    cost_template_id bigint REFERENCES inventory_cost_templates(id) ON DELETE SET NULL,
    note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shop_key, ticket_no)
);

ALTER TABLE inventory_tickets
    ADD COLUMN IF NOT EXISTS cost_template_id bigint REFERENCES inventory_cost_templates(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_inventory_tickets_shop_updated
    ON inventory_tickets (shop_key, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_inventory_tickets_template
    ON inventory_tickets (cost_template_id);

CREATE TABLE IF NOT EXISTS inventory_ticket_lines (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_ticket_id bigint NOT NULL REFERENCES inventory_tickets(id) ON DELETE CASCADE,
    warehouse_sku text NOT NULL,
    quantity numeric NOT NULL DEFAULT 0,
    unit_price numeric,
    amount numeric,
    note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (inventory_ticket_id, warehouse_sku)
);

CREATE INDEX IF NOT EXISTS idx_inventory_ticket_lines_ticket
    ON inventory_ticket_lines (inventory_ticket_id, id);

CREATE INDEX IF NOT EXISTS idx_inventory_ticket_lines_warehouse
    ON inventory_ticket_lines (warehouse_sku);

CREATE TABLE IF NOT EXISTS inventory_cost_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_key text NOT NULL,
    template_id bigint REFERENCES inventory_cost_templates(id) ON DELETE CASCADE,
    name text NOT NULL,
    currency text NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (shop_key, name),
    CHECK (currency ~ '^[A-Z][A-Z0-9]{1,7}$')
);

ALTER TABLE inventory_cost_categories
    ADD COLUMN IF NOT EXISTS template_id bigint REFERENCES inventory_cost_templates(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_inventory_cost_categories_shop_sort
    ON inventory_cost_categories (shop_key, sort_order, id);

CREATE INDEX IF NOT EXISTS idx_inventory_cost_categories_template_sort
    ON inventory_cost_categories (template_id, sort_order, id);

CREATE TABLE IF NOT EXISTS inventory_template_settings (
    shop_key text PRIMARY KEY,
    initialized_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS inventory_cost_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES inventory_cost_categories(id) ON DELETE CASCADE,
    name text NOT NULL,
    calculation_mode text NOT NULL DEFAULT 'quantity_x_unit',
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (category_id, name),
    CHECK (calculation_mode IN ('direct_amount', 'quantity_x_unit'))
);

CREATE INDEX IF NOT EXISTS idx_inventory_cost_types_category_sort
    ON inventory_cost_types (category_id, sort_order, id);

CREATE TABLE IF NOT EXISTS inventory_cost_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_ticket_id bigint NOT NULL REFERENCES inventory_tickets(id) ON DELETE CASCADE,
    cost_type_id bigint NOT NULL REFERENCES inventory_cost_types(id) ON DELETE CASCADE,
    quantity numeric,
    unit_price numeric,
    amount numeric,
    note text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (inventory_ticket_id, cost_type_id)
);

CREATE INDEX IF NOT EXISTS idx_inventory_cost_entries_ticket
    ON inventory_cost_entries (inventory_ticket_id, cost_type_id);

DO $$
DECLARE
    migration_name constant text := 'inventory_tickets_dynamic_costs_v1';
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM inventory_schema_migrations WHERE migration_key = migration_name
    ) THEN
        IF to_regclass('public.shein_inventory_records') IS NOT NULL THEN
            INSERT INTO inventory_tickets (shop_key, ticket_no, created_at, updated_at)
            SELECT shop_key, order_no, MIN(created_at), MAX(updated_at)
            FROM shein_inventory_records
            GROUP BY shop_key, order_no
            ON CONFLICT (shop_key, ticket_no) DO NOTHING;

            INSERT INTO inventory_ticket_lines (
                inventory_ticket_id, warehouse_sku, quantity, unit_price, amount, note, created_at, updated_at
            )
            SELECT t.id, r.warehouse_sku, r.quantity, r.unit_price, r.amount, r.note, r.created_at, r.updated_at
            FROM shein_inventory_records r
            JOIN inventory_tickets t
              ON t.shop_key = r.shop_key AND t.ticket_no = r.order_no
            ON CONFLICT (inventory_ticket_id, warehouse_sku) DO NOTHING;
        END IF;

        INSERT INTO inventory_cost_categories (shop_key, name, currency, sort_order)
        SELECT shops.shop_key, seed.name, seed.currency, seed.sort_order
        FROM (SELECT DISTINCT shop_key FROM inventory_tickets) shops
        CROSS JOIN (VALUES
            ('出口代理费用', 'RMB', 10),
            ('海运进口费用', 'USD', 20),
            ('入仓费用', 'USD', 30)
        ) AS seed(name, currency, sort_order)
        ON CONFLICT (shop_key, name) DO NOTHING;

        INSERT INTO inventory_cost_types (category_id, name, calculation_mode, sort_order)
        SELECT c.id, seed.name, 'quantity_x_unit', seed.sort_order
        FROM inventory_cost_categories c
        JOIN (VALUES
            ('出口代理费用', '拖车费-起运港', 10),
            ('出口代理费用', '港杂物费', 20),
            ('海运进口费用', '税金', 10),
            ('海运进口费用', '尾程派送费', 20),
            ('海运进口费用', '美国反恐舱单费', 30),
            ('海运进口费用', '海运费', 40),
            ('入仓费用', '待时费', 10),
            ('入仓费用', '卸货费', 20)
        ) AS seed(category_name, name, sort_order)
          ON seed.category_name = c.name
        ON CONFLICT (category_id, name) DO NOTHING;

        INSERT INTO inventory_template_settings (shop_key)
        SELECT DISTINCT shop_key FROM inventory_tickets
        ON CONFLICT (shop_key) DO NOTHING;

        IF to_regclass('public.shein_inventory_export_agent_fees') IS NOT NULL THEN
            INSERT INTO inventory_cost_entries (
                inventory_ticket_id, cost_type_id, quantity, unit_price, amount, note, created_at, updated_at
            )
            SELECT t.id, ct.id,
                   CASE
                       WHEN f.quantity IS NOT NULL AND f.unit_price IS NOT NULL THEN f.quantity
                       WHEN f.amount IS NOT NULL THEN 1
                       ELSE NULL
                   END,
                   CASE
                       WHEN f.quantity IS NOT NULL AND f.unit_price IS NOT NULL THEN f.unit_price
                       WHEN f.amount IS NOT NULL THEN f.amount
                       ELSE NULL
                   END,
                   CASE
                       WHEN f.quantity IS NOT NULL AND f.unit_price IS NOT NULL THEN f.quantity * f.unit_price
                       ELSE f.amount
                   END,
                   f.note, f.created_at, f.updated_at
            FROM shein_inventory_export_agent_fees f
            JOIN inventory_tickets t ON t.shop_key = f.shop_key AND t.ticket_no = f.order_no
            JOIN inventory_cost_categories c ON c.shop_key = f.shop_key AND c.name = '出口代理费用'
            JOIN inventory_cost_types ct ON ct.category_id = c.id AND ct.name = CASE f.fee_type
                WHEN 'origin_trucking' THEN '拖车费-起运港'
                WHEN 'port_misc' THEN '港杂物费'
                ELSE f.fee_type
            END
            WHERE f.quantity IS NOT NULL OR f.unit_price IS NOT NULL OR f.amount IS NOT NULL
               OR NULLIF(BTRIM(f.note), '') IS NOT NULL
            ON CONFLICT (inventory_ticket_id, cost_type_id) DO NOTHING;
        END IF;

        IF to_regclass('public.shein_inventory_ocean_import_fees') IS NOT NULL THEN
            INSERT INTO inventory_cost_entries (
                inventory_ticket_id, cost_type_id, quantity, unit_price, amount, note, created_at, updated_at
            )
            SELECT t.id, ct.id,
                   CASE
                       WHEN f.quantity IS NOT NULL AND f.unit_price IS NOT NULL THEN f.quantity
                       WHEN f.amount IS NOT NULL THEN 1
                       ELSE NULL
                   END,
                   CASE
                       WHEN f.quantity IS NOT NULL AND f.unit_price IS NOT NULL THEN f.unit_price
                       WHEN f.amount IS NOT NULL THEN f.amount
                       ELSE NULL
                   END,
                   CASE
                       WHEN f.quantity IS NOT NULL AND f.unit_price IS NOT NULL THEN f.quantity * f.unit_price
                       ELSE f.amount
                   END,
                   f.note, f.created_at, f.updated_at
            FROM shein_inventory_ocean_import_fees f
            JOIN inventory_tickets t ON t.shop_key = f.shop_key AND t.ticket_no = f.order_no
            JOIN inventory_cost_categories c ON c.shop_key = f.shop_key AND c.name = '海运进口费用'
            JOIN inventory_cost_types ct ON ct.category_id = c.id AND ct.name = CASE f.fee_type
                WHEN 'tax' THEN '税金'
                WHEN 'final_delivery' THEN '尾程派送费'
                WHEN 'ams' THEN '美国反恐舱单费'
                WHEN 'ocean_freight' THEN '海运费'
                ELSE f.fee_type
            END
            WHERE f.quantity IS NOT NULL OR f.unit_price IS NOT NULL OR f.amount IS NOT NULL
               OR NULLIF(BTRIM(f.note), '') IS NOT NULL
            ON CONFLICT (inventory_ticket_id, cost_type_id) DO NOTHING;
        END IF;

        IF to_regclass('public.shein_inventory_inbound_fees') IS NOT NULL THEN
            INSERT INTO inventory_cost_entries (
                inventory_ticket_id, cost_type_id, quantity, unit_price, amount, note, created_at, updated_at
            )
            SELECT t.id, ct.id,
                   CASE
                       WHEN f.quantity IS NOT NULL AND f.unit_price IS NOT NULL THEN f.quantity
                       WHEN f.amount IS NOT NULL THEN 1
                       ELSE NULL
                   END,
                   CASE
                       WHEN f.quantity IS NOT NULL AND f.unit_price IS NOT NULL THEN f.unit_price
                       WHEN f.amount IS NOT NULL THEN f.amount
                       ELSE NULL
                   END,
                   CASE
                       WHEN f.quantity IS NOT NULL AND f.unit_price IS NOT NULL THEN f.quantity * f.unit_price
                       ELSE f.amount
                   END,
                   f.note, f.created_at, f.updated_at
            FROM shein_inventory_inbound_fees f
            JOIN inventory_tickets t ON t.shop_key = f.shop_key AND t.ticket_no = f.order_no
            JOIN inventory_cost_categories c ON c.shop_key = f.shop_key AND c.name = '入仓费用'
            JOIN inventory_cost_types ct ON ct.category_id = c.id AND ct.name = CASE f.fee_type
                WHEN 'waiting_fee' THEN '待时费'
                WHEN 'unloading_fee' THEN '卸货费'
                ELSE f.fee_type
            END
            WHERE f.quantity IS NOT NULL OR f.unit_price IS NOT NULL OR f.amount IS NOT NULL
               OR NULLIF(BTRIM(f.note), '') IS NOT NULL
            ON CONFLICT (inventory_ticket_id, cost_type_id) DO NOTHING;
        END IF;

        INSERT INTO inventory_schema_migrations (migration_key) VALUES (migration_name);
    END IF;
END $$;

DO $$
DECLARE
    migration_name constant text := 'inventory_named_cost_templates_v2';
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM inventory_schema_migrations WHERE migration_key = migration_name
    ) THEN
        INSERT INTO inventory_cost_templates (shop_key, name)
        SELECT shops.shop_key, '标准库存成本模板'
        FROM (
            SELECT DISTINCT shop_key FROM inventory_cost_categories
            UNION
            SELECT DISTINCT shop_key FROM inventory_tickets
        ) shops
        ON CONFLICT (shop_key, name) DO NOTHING;

        UPDATE inventory_cost_categories c
        SET template_id = t.id
        FROM inventory_cost_templates t
        WHERE c.template_id IS NULL
          AND t.shop_key = c.shop_key
          AND t.name = '标准库存成本模板';

        UPDATE inventory_tickets i
        SET cost_template_id = t.id
        FROM inventory_cost_templates t
        WHERE i.cost_template_id IS NULL
          AND t.shop_key = i.shop_key
          AND t.name = '标准库存成本模板';

        INSERT INTO inventory_schema_migrations (migration_key) VALUES (migration_name);
    END IF;
END $$;

ALTER TABLE inventory_cost_categories
    ALTER COLUMN template_id SET NOT NULL;

ALTER TABLE inventory_cost_categories
    DROP CONSTRAINT IF EXISTS inventory_cost_categories_shop_key_name_key;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'inventory_cost_categories_template_name_key'
    ) THEN
        ALTER TABLE inventory_cost_categories
            ADD CONSTRAINT inventory_cost_categories_template_name_key
            UNIQUE (template_id, name);
    END IF;
END $$;
"""


def ensure_inventory_schema(database_url: str) -> None:
    with connect(database_url) as conn:
        conn.execute(INVENTORY_SCHEMA_SQL)


def list_sku_mappings(database_url: str, *, shop_key: str, search: str | None = None) -> list[dict[str, Any]]:
    filters = ["shop_key = %s"]
    params: list[Any] = [shop_key]
    if search:
        filters.append("(warehouse_sku ILIKE %s OR shein_sku ILIKE %s OR COALESCE(note, '') ILIKE %s)")
        term = f"%{search.strip()}%"
        params.extend([term, term, term])
    where_sql = " AND ".join(filters)
    with connect(database_url) as conn:
        rows = conn.execute(
            f"""
            SELECT id, shop_key, warehouse_sku, shein_sku, sku_group, warehouse_qty,
                   length_cm, width_cm, height_cm, weight_kg, cost_price,
                   purchase_price, ocean_freight_price, note, enabled,
                   created_at, updated_at
            FROM shein_sku_mappings
            WHERE {where_sql}
            ORDER BY enabled DESC, warehouse_sku, shein_sku, id
            """,
            params,
        ).fetchall()
    return [
        {
            "id": row[0],
            "shop_key": row[1],
            "warehouse_sku": row[2],
            "shein_sku": row[3],
            "sku_group": row[4],
            "warehouse_qty": row[5],
            "length_cm": row[6],
            "width_cm": row[7],
            "height_cm": row[8],
            "weight_kg": row[9],
            "cost_price": row[10],
            "purchase_price": row[11],
            "ocean_freight_price": row[12],
            "note": row[13],
            "enabled": row[14],
            "created_at": row[15],
            "updated_at": row[16],
        }
        for row in rows
    ]


def upsert_sku_mapping(
    database_url: str,
    *,
    shop_key: str,
    warehouse_sku: str,
    shein_sku: str,
    warehouse_qty: Any = 1,
    length_cm: Any = None,
    width_cm: Any = None,
    height_cm: Any = None,
    weight_kg: Any = None,
    cost_price: Any = None,
    purchase_price: Any = None,
    ocean_freight_price: Any = None,
    note: str | None = None,
    sku_group: str = "default",
    enabled: bool = True,
    mapping_id: int | None = None,
) -> tuple[dict[str, Any], bool]:
    with connect(database_url) as conn:
        if mapping_id:
            row = conn.execute(
                """
                UPDATE shein_sku_mappings
                SET warehouse_sku = %s,
                    shein_sku = %s,
                    sku_group = %s,
                    warehouse_qty = %s,
                    length_cm = %s,
                    width_cm = %s,
                    height_cm = %s,
                    weight_kg = %s,
                    cost_price = COALESCE(%s, cost_price),
                    purchase_price = %s,
                    ocean_freight_price = %s,
                    note = %s,
                    enabled = %s,
                    updated_at = now()
                WHERE id = %s AND shop_key = %s
                RETURNING id, shop_key, warehouse_sku, shein_sku, sku_group, warehouse_qty,
                          length_cm, width_cm, height_cm, weight_kg, cost_price,
                          purchase_price, ocean_freight_price, note,
                          enabled, created_at, updated_at
                """,
                (
                    warehouse_sku,
                    shein_sku,
                    sku_group,
                    warehouse_qty,
                    length_cm,
                    width_cm,
                    height_cm,
                    weight_kg,
                    cost_price,
                    purchase_price,
                    ocean_freight_price,
                    note,
                    enabled,
                    mapping_id,
                    shop_key,
                ),
            ).fetchone()
            if not row:
                raise KeyError(f"SKU mapping not found: {mapping_id}")
            inserted = False
        else:
            existing = conn.execute(
                """
                SELECT id
                FROM shein_sku_mappings
                WHERE shop_key = %s AND shein_sku = %s
                ORDER BY enabled DESC, updated_at DESC, id DESC
                LIMIT 1
                """,
                (shop_key, shein_sku),
            ).fetchone()
            if existing:
                row = conn.execute(
                    """
                    UPDATE shein_sku_mappings
                    SET warehouse_sku = %s,
                        sku_group = %s,
                        warehouse_qty = %s,
                        length_cm = %s,
                        width_cm = %s,
                        height_cm = %s,
                        weight_kg = %s,
                        cost_price = COALESCE(%s, cost_price),
                        purchase_price = %s,
                        ocean_freight_price = %s,
                        note = %s,
                        enabled = %s,
                        updated_at = now()
                    WHERE id = %s AND shop_key = %s
                    RETURNING id, shop_key, warehouse_sku, shein_sku, sku_group, warehouse_qty,
                              length_cm, width_cm, height_cm, weight_kg, cost_price,
                              purchase_price, ocean_freight_price, note,
                              enabled, created_at, updated_at
                    """,
                    (
                        warehouse_sku,
                        sku_group,
                        warehouse_qty,
                        length_cm,
                        width_cm,
                        height_cm,
                        weight_kg,
                        cost_price,
                        purchase_price,
                        ocean_freight_price,
                        note,
                        enabled,
                        existing[0],
                        shop_key,
                    ),
                ).fetchone()
                inserted = False
            else:
                row = conn.execute(
                    """
                    INSERT INTO shein_sku_mappings (
                        shop_key, warehouse_sku, shein_sku, sku_group, warehouse_qty,
                        length_cm, width_cm, height_cm, weight_kg, cost_price,
                        purchase_price, ocean_freight_price, note, enabled
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (shop_key, warehouse_sku, shein_sku) DO UPDATE SET
                        sku_group = EXCLUDED.sku_group,
                        warehouse_qty = EXCLUDED.warehouse_qty,
                        length_cm = EXCLUDED.length_cm,
                        width_cm = EXCLUDED.width_cm,
                        height_cm = EXCLUDED.height_cm,
                        weight_kg = EXCLUDED.weight_kg,
                        cost_price = COALESCE(EXCLUDED.cost_price, shein_sku_mappings.cost_price),
                        purchase_price = EXCLUDED.purchase_price,
                        ocean_freight_price = EXCLUDED.ocean_freight_price,
                        note = EXCLUDED.note,
                        enabled = EXCLUDED.enabled,
                        updated_at = now()
                    RETURNING id, shop_key, warehouse_sku, shein_sku, sku_group, warehouse_qty,
                              length_cm, width_cm, height_cm, weight_kg, cost_price,
                              purchase_price, ocean_freight_price, note,
                              enabled, created_at, updated_at, (xmax = 0) AS inserted
                    """,
                    (
                        shop_key,
                        warehouse_sku,
                        shein_sku,
                        sku_group,
                        warehouse_qty,
                        length_cm,
                        width_cm,
                        height_cm,
                        weight_kg,
                        cost_price,
                        purchase_price,
                        ocean_freight_price,
                        note,
                        enabled,
                    ),
                ).fetchone()
                inserted = bool(row[17])
    return (
        {
            "id": row[0],
            "shop_key": row[1],
            "warehouse_sku": row[2],
            "shein_sku": row[3],
            "sku_group": row[4],
            "warehouse_qty": row[5],
            "length_cm": row[6],
            "width_cm": row[7],
            "height_cm": row[8],
            "weight_kg": row[9],
            "cost_price": row[10],
            "purchase_price": row[11],
            "ocean_freight_price": row[12],
            "note": row[13],
            "enabled": row[14],
            "created_at": row[15],
            "updated_at": row[16],
        },
        inserted,
    )


def delete_sku_mapping(database_url: str, *, shop_key: str, mapping_id: int) -> bool:
    with connect(database_url) as conn:
        result = conn.execute(
            "DELETE FROM shein_sku_mappings WHERE id = %s AND shop_key = %s",
            (mapping_id, shop_key),
        )
    return bool(result.rowcount)


def normalize_warehouse_sku_value(value: Any) -> str:
    return str(value or "").strip()


def serialize_warehouse_sku_row(row: Any) -> dict[str, Any]:
    return {
        "id": row[0],
        "shop_key": row[1],
        "warehouse_sku": row[2],
        "length_cm": row[3],
        "width_cm": row[4],
        "height_cm": row[5],
        "weight_kg": row[6],
        "cost_price": row[7],
        "purchase_price": row[8],
        "ocean_freight_price": row[9],
        "operation_fee_price": row[10],
        "note": row[11],
        "enabled": row[12],
        "created_at": row[13],
        "updated_at": row[14],
    }


def list_warehouse_skus(
    database_url: str,
    *,
    shop_key: str,
    search: str | None = None,
    include_disabled: bool = False,
) -> list[dict[str, Any]]:
    ensure_sku_mapping_schema(database_url)
    filters = ["shop_key = %s"]
    params: list[Any] = [shop_key]
    if not include_disabled:
        filters.append("enabled = true")
    if search:
        filters.append("(warehouse_sku ILIKE %s OR COALESCE(note, '') ILIKE %s)")
        term = f"%{search.strip()}%"
        params.extend([term, term])
    where_sql = " AND ".join(filters)
    with connect(database_url) as conn:
        rows = conn.execute(
            f"""
            SELECT id, shop_key, warehouse_sku, length_cm, width_cm, height_cm, weight_kg,
                   cost_price, purchase_price, ocean_freight_price, operation_fee_price,
                   note, enabled, created_at, updated_at
            FROM shein_warehouse_skus
            WHERE {where_sql}
            ORDER BY enabled DESC, warehouse_sku, id
            """,
            params,
        ).fetchall()
    return [serialize_warehouse_sku_row(row) for row in rows]


def upsert_warehouse_sku(
    database_url: str,
    *,
    shop_key: str,
    warehouse_sku: str,
    length_cm: Any = None,
    width_cm: Any = None,
    height_cm: Any = None,
    weight_kg: Any = None,
    cost_price: Any = None,
    purchase_price: Any = None,
    ocean_freight_price: Any = None,
    operation_fee_price: Any = None,
    note: str | None = None,
    enabled: bool = True,
    preserve_existing_values: bool = False,
) -> tuple[dict[str, Any], bool]:
    ensure_sku_mapping_schema(database_url)
    normalized = normalize_warehouse_sku_value(warehouse_sku)
    if not normalized:
        raise ValueError("warehouse_sku is required")
    with connect(database_url) as conn:
        row = conn.execute(
            """
            INSERT INTO shein_warehouse_skus (
                shop_key, warehouse_sku, length_cm, width_cm, height_cm, weight_kg,
                cost_price, purchase_price, ocean_freight_price, operation_fee_price, note, enabled
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, COALESCE(%s, 0), %s, %s)
            ON CONFLICT (shop_key, warehouse_sku) DO UPDATE SET
                length_cm = CASE WHEN %s THEN COALESCE(EXCLUDED.length_cm, shein_warehouse_skus.length_cm) ELSE EXCLUDED.length_cm END,
                width_cm = CASE WHEN %s THEN COALESCE(EXCLUDED.width_cm, shein_warehouse_skus.width_cm) ELSE EXCLUDED.width_cm END,
                height_cm = CASE WHEN %s THEN COALESCE(EXCLUDED.height_cm, shein_warehouse_skus.height_cm) ELSE EXCLUDED.height_cm END,
                weight_kg = CASE WHEN %s THEN COALESCE(EXCLUDED.weight_kg, shein_warehouse_skus.weight_kg) ELSE EXCLUDED.weight_kg END,
                cost_price = CASE WHEN %s THEN COALESCE(EXCLUDED.cost_price, shein_warehouse_skus.cost_price) ELSE COALESCE(EXCLUDED.cost_price, shein_warehouse_skus.cost_price) END,
                purchase_price = CASE WHEN %s THEN COALESCE(EXCLUDED.purchase_price, shein_warehouse_skus.purchase_price) ELSE EXCLUDED.purchase_price END,
                ocean_freight_price = CASE WHEN %s THEN COALESCE(EXCLUDED.ocean_freight_price, shein_warehouse_skus.ocean_freight_price) ELSE EXCLUDED.ocean_freight_price END,
                operation_fee_price = CASE WHEN %s THEN COALESCE(%s, shein_warehouse_skus.operation_fee_price) ELSE EXCLUDED.operation_fee_price END,
                note = COALESCE(EXCLUDED.note, shein_warehouse_skus.note),
                enabled = EXCLUDED.enabled,
                updated_at = now()
            RETURNING id, shop_key, warehouse_sku, length_cm, width_cm, height_cm, weight_kg,
                      cost_price, purchase_price, ocean_freight_price, operation_fee_price, note, enabled,
                      created_at, updated_at, (xmax = 0) AS inserted
            """,
            (
                shop_key,
                normalized,
                length_cm,
                width_cm,
                height_cm,
                weight_kg,
                cost_price,
                purchase_price,
                ocean_freight_price,
                operation_fee_price,
                note,
                enabled,
                preserve_existing_values,
                preserve_existing_values,
                preserve_existing_values,
                preserve_existing_values,
                preserve_existing_values,
                preserve_existing_values,
                preserve_existing_values,
                preserve_existing_values,
                operation_fee_price,
            ),
        ).fetchone()
    data = serialize_warehouse_sku_row(row)
    return data, bool(row[15])


def bulk_upsert_warehouse_skus(database_url: str, *, shop_key: str, warehouse_skus: list[str]) -> dict[str, Any]:
    inserted = 0
    updated = 0
    skipped = 0
    rows: list[dict[str, Any]] = []
    seen: set[str] = set()
    for raw in warehouse_skus:
        sku = normalize_warehouse_sku_value(raw)
        if not sku or sku in seen:
            skipped += 1
            continue
        seen.add(sku)
        row, is_inserted = upsert_warehouse_sku(
            database_url,
            shop_key=shop_key,
            warehouse_sku=sku,
            preserve_existing_values=True,
        )
        rows.append(row)
        inserted += 1 if is_inserted else 0
        updated += 0 if is_inserted else 1
    return {"inserted": inserted, "updated": updated, "skipped": skipped, "rows": rows}


def get_sku_mapping_settings(database_url: str, *, shop_key: str) -> dict[str, Any]:
    ensure_sku_mapping_schema(database_url)
    with connect(database_url) as conn:
        row = conn.execute(
            """
            SELECT default_warehouse_sku, created_at, updated_at
            FROM shein_sku_mapping_settings
            WHERE shop_key = %s
            """,
            (shop_key,),
        ).fetchone()
    if not row:
        return {"default_warehouse_sku": "", "created_at": None, "updated_at": None}
    return {"default_warehouse_sku": row[0] or "", "created_at": row[1], "updated_at": row[2]}


def save_sku_mapping_settings(database_url: str, *, shop_key: str, default_warehouse_sku: str | None) -> dict[str, Any]:
    ensure_sku_mapping_schema(database_url)
    normalized = (default_warehouse_sku or "").strip() or None
    with connect(database_url) as conn:
        row = conn.execute(
            """
            INSERT INTO shein_sku_mapping_settings (shop_key, default_warehouse_sku)
            VALUES (%s, %s)
            ON CONFLICT (shop_key) DO UPDATE SET
                default_warehouse_sku = EXCLUDED.default_warehouse_sku,
                updated_at = now()
            RETURNING default_warehouse_sku, created_at, updated_at
            """,
            (shop_key, normalized),
        ).fetchone()
    return {"default_warehouse_sku": row[0] or "", "created_at": row[1], "updated_at": row[2]}


def save_shop(
    database_url: str,
    *,
    shop_key: str,
    open_key_id: str,
    secret_key: str,
    base_url: str,
    shop_name: str | None = None,
    schema_name: str | None = None,
    app_id: str | None = None,
    state: str | None = None,
    enabled: bool = True,
) -> None:
    shop_key = shop_key.strip()
    if not SHOP_CODE_PATTERN.fullmatch(shop_key):
        raise ValueError("shop_key must use lowercase letters, digits, and hyphens")
    shop_name = (shop_name or shop_key).strip()
    if not shop_name:
        raise ValueError("shop_name is required")
    schema_name = (schema_name or f"shein_{shop_key.replace('-', '_')}").strip()
    if not SCHEMA_NAME_PATTERN.fullmatch(schema_name):
        raise ValueError("schema_name must use lowercase letters, digits, and underscores")
    init_registry(database_url)
    with psycopg.connect(database_url) as conn:
        conn.execute(sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(sql.Identifier(schema_name)))
        conn.execute(
            """
            INSERT INTO public.shein_shops (
                shop_key, shop_name, schema_name, app_id, open_key_id, secret_key, base_url, state, enabled
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (shop_key) DO UPDATE SET
                shop_name = EXCLUDED.shop_name,
                schema_name = EXCLUDED.schema_name,
                app_id = EXCLUDED.app_id,
                open_key_id = EXCLUDED.open_key_id,
                secret_key = EXCLUDED.secret_key,
                base_url = EXCLUDED.base_url,
                state = EXCLUDED.state,
                enabled = EXCLUDED.enabled,
                updated_at = now()
            """,
            (shop_key, shop_name, schema_name, app_id, open_key_id, secret_key, base_url, state, enabled),
        )
    shop_database_url.cache_clear()
    init_shop_schema(database_url, shop_key)


def load_shop(database_url: str, shop_key: str) -> StoreCredentials:
    with psycopg.connect(database_url) as conn:
        row = conn.execute(
            "SELECT shop_key, open_key_id, secret_key, base_url FROM public.shein_shops WHERE shop_key = %s AND enabled = true",
            (shop_key,),
        ).fetchone()
    if not row:
        raise KeyError(f"shop_key not found in shein_shops: {shop_key}")
    return StoreCredentials(shop_key=row[0], open_key_id=row[1], secret_key=row[2], base_url=row[3])




def upsert_product(
    database_url: str,
    *,
    shop_key: str,
    skc_name: str,
    raw_payload: dict[str, Any],
    spu_name: str | None = None,
    sku_code_list: list[str] | None = None,
) -> bool:
    with connect(database_url) as conn:
        row = conn.execute(
            """
            INSERT INTO shein_products (shop_key, spu_name, skc_name, sku_code_list, raw_payload)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (shop_key, skc_name) DO UPDATE SET
                spu_name = COALESCE(EXCLUDED.spu_name, shein_products.spu_name),
                sku_code_list = EXCLUDED.sku_code_list,
                raw_payload = EXCLUDED.raw_payload,
                last_seen_at = now()
            RETURNING (xmax = 0) AS inserted
            """,
            (shop_key, spu_name, skc_name, Jsonb(sku_code_list or []), Jsonb(raw_payload)),
        ).fetchone()
    return bool(row[0])


def upsert_product_detail(
    database_url: str,
    *,
    shop_key: str,
    spu_name: str,
    raw_payload: dict[str, Any],
    spu_shelf_status: int | None = None,
    category_id: str | None = None,
    skc_list: list[dict[str, Any]] | None = None,
) -> bool:
    with connect(database_url) as conn:
        row = conn.execute(
            """
            INSERT INTO shein_product_details (
                shop_key, spu_name, spu_shelf_status, category_id, skc_list, raw_payload
            )
            VALUES (%s, %s, %s, %s, %s, %s)
            ON CONFLICT (shop_key, spu_name) DO UPDATE SET
                spu_shelf_status = COALESCE(EXCLUDED.spu_shelf_status, shein_product_details.spu_shelf_status),
                category_id = COALESCE(EXCLUDED.category_id, shein_product_details.category_id),
                skc_list = EXCLUDED.skc_list,
                raw_payload = EXCLUDED.raw_payload,
                detail_fetched_at = now(),
                last_seen_at = now()
            RETURNING (xmax = 0) AS inserted
            """,
            (shop_key, spu_name, spu_shelf_status, category_id, Jsonb(skc_list or []), Jsonb(raw_payload)),
        ).fetchone()
    return bool(row[0])


def list_product_sku_options(database_url: str, *, shop_key: str) -> list[dict[str, Any]]:
    ensure_product_schema(database_url)
    options: dict[str, dict[str, Any]] = {}
    with connect(database_url) as conn:
        product_rows = conn.execute(
            """
            SELECT spu_name, skc_name, sku_code_list, raw_payload, last_seen_at
            FROM shein_products
            WHERE shop_key = %s
            ORDER BY last_seen_at DESC, spu_name, skc_name
            """,
            (shop_key,),
        ).fetchall()
        detail_rows = conn.execute(
            """
            SELECT spu_name, skc_list, raw_payload, last_seen_at
            FROM shein_product_details
            WHERE shop_key = %s
            ORDER BY last_seen_at DESC, spu_name
            """,
            (shop_key,),
        ).fetchall()

    for row in product_rows:
        spu_name = _text_or_none(row[0])
        skc_name = _text_or_none(row[1])
        for sku_code in _json_string_list(row[2]):
            _remember_product_sku_option(
                options,
                sku_code=sku_code,
                spu_name=spu_name,
                skc_name=skc_name,
                last_seen_at=row[4],
            )

    for row in detail_rows:
        spu_name = _text_or_none(row[0])
        skc_items = row[1] if isinstance(row[1], list) else []
        for skc in skc_items:
            if not isinstance(skc, dict):
                continue
            skc_name = _text_or_none(skc.get("skcName") or skc.get("skc_name"))
            title = _localized_product_text(skc.get("skcTitle"), "title")
            supplier_code = _text_or_none(skc.get("supplierCode") or skc.get("supplier_code"))
            main_pic_url = _text_or_none(skc.get("skcMainPicUrl") or skc.get("skc_main_pic_url"))
            sku_items = skc.get("skuList") if isinstance(skc.get("skuList"), list) else []
            for sku in sku_items:
                if not isinstance(sku, dict):
                    continue
                sku_code = _text_or_none(sku.get("skuCode") or sku.get("sku_code"))
                if not sku_code:
                    continue
                _remember_product_sku_option(
                    options,
                    sku_code=sku_code,
                    spu_name=spu_name,
                    skc_name=skc_name,
                    supplier_code=supplier_code,
                    supplier_sku=_text_or_none(sku.get("supplierSku") or sku.get("supplier_sku")),
                    title=title,
                    main_pic_url=main_pic_url,
                    last_seen_at=row[3],
                )
    return sorted(options.values(), key=lambda item: (item.get("title") or "", item["sku_code"]))


def _remember_product_sku_option(
    options: dict[str, dict[str, Any]],
    *,
    sku_code: str,
    spu_name: str | None = None,
    skc_name: str | None = None,
    supplier_code: str | None = None,
    supplier_sku: str | None = None,
    title: str | None = None,
    main_pic_url: str | None = None,
    last_seen_at: Any = None,
) -> None:
    existing = options.setdefault(
        sku_code,
        {
            "sku_code": sku_code,
            "spu_name": None,
            "skc_name": None,
            "supplier_code": None,
            "supplier_sku": None,
            "title": None,
            "main_pic_url": None,
            "last_seen_at": None,
        },
    )
    for key, value in {
        "spu_name": spu_name,
        "skc_name": skc_name,
        "supplier_code": supplier_code,
        "supplier_sku": supplier_sku,
        "title": title,
        "main_pic_url": main_pic_url,
        "last_seen_at": last_seen_at,
    }.items():
        if value not in (None, ""):
            existing[key] = value


def _json_string_list(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if str(item or "").strip()]


def _text_or_none(value: Any) -> str | None:
    if value in (None, ""):
        return None
    text = str(value).strip()
    return text or None


def _localized_product_text(value: Any, key: str) -> str | None:
    if not isinstance(value, list):
        return None
    preferred = ("zh-cn", "en", "fr", "es", "de", "pt-br", "th", "ja", "ko")
    by_language: dict[str, str] = {}
    fallback: str | None = None
    for item in value:
        if not isinstance(item, dict):
            continue
        text = _text_or_none(item.get(key))
        if not text:
            continue
        language = str(item.get("language") or "").lower()
        if language:
            by_language[language] = text
        fallback = fallback or text
    for language in preferred:
        if language in by_language:
            return by_language[language]
    return fallback

def create_sync_run(database_url: str, *, shop_key: str, query_params: dict[str, Any]) -> int:
    with connect(database_url) as conn:
        row = conn.execute(
            """
            INSERT INTO shein_sync_runs (shop_key, status, query_params)
            VALUES (%s, 'running', %s)
            RETURNING id
            """,
            (shop_key, Jsonb(query_params)),
        ).fetchone()
    return int(row[0])


def finish_sync_run(
    database_url: str,
    *,
    run_id: int,
    status: str,
    pages: int,
    orders_seen: int,
    orders_upserted: int,
    error: str | None = None,
) -> None:
    with connect(database_url) as conn:
        conn.execute(
            """
            UPDATE shein_sync_runs
            SET status = %s,
                finished_at = now(),
                pages = %s,
                orders_seen = %s,
                orders_upserted = %s,
                error = %s
            WHERE id = %s
            """,
            (status, pages, orders_seen, orders_upserted, error, run_id),
        )


def upsert_order(
    database_url: str,
    *,
    shop_key: str,
    order_no: str,
    list_payload: dict[str, Any],
    order_status: str | None = None,
    order_status_label: str | None = None,
    order_status_normalized: str = "unknown",
    order_type: str | None = None,
    order_type_label: str | None = None,
    order_created_at: str | None = None,
    order_updated_at: str | None = None,
    return_detected: bool = False,
    return_status: str = "none",
    order_return_time: str | None = None,
    return_evidence: list[dict[str, Any]] | None = None,
) -> bool:
    with connect(database_url) as conn:
        row = conn.execute(
            """
            INSERT INTO shein_orders (
                shop_key, order_no, order_status, order_status_label, order_status_normalized,
                order_type, order_type_label,
                order_created_at, order_updated_at, return_detected, return_status, order_return_time,
                return_evidence, list_payload
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (shop_key, order_no) DO UPDATE SET
                order_status = COALESCE(EXCLUDED.order_status, shein_orders.order_status),
                order_status_label = COALESCE(EXCLUDED.order_status_label, shein_orders.order_status_label),
                order_status_normalized = CASE
                    WHEN EXCLUDED.order_status_normalized <> 'unknown' THEN EXCLUDED.order_status_normalized
                    ELSE shein_orders.order_status_normalized
                END,
                order_type = COALESCE(EXCLUDED.order_type, shein_orders.order_type),
                order_type_label = COALESCE(EXCLUDED.order_type_label, shein_orders.order_type_label),
                order_created_at = COALESCE(EXCLUDED.order_created_at, shein_orders.order_created_at),
                order_updated_at = COALESCE(EXCLUDED.order_updated_at, shein_orders.order_updated_at),
                return_detected = EXCLUDED.return_detected OR shein_orders.return_detected,
                return_status = CASE
                    WHEN EXCLUDED.return_status <> 'none' THEN EXCLUDED.return_status
                    ELSE shein_orders.return_status
                END,
                order_return_time = COALESCE(EXCLUDED.order_return_time, shein_orders.order_return_time),
                return_evidence = CASE
                    WHEN EXCLUDED.return_evidence <> '[]'::jsonb THEN EXCLUDED.return_evidence
                    ELSE shein_orders.return_evidence
                END,
                list_payload = EXCLUDED.list_payload,
                last_seen_at = now()
            RETURNING (xmax = 0) AS inserted
            """,
            (
                shop_key,
                order_no,
                order_status,
                order_status_label,
                order_status_normalized,
                order_type,
                order_type_label,
                order_created_at,
                order_updated_at,
                return_detected,
                return_status,
                order_return_time,
                Jsonb(return_evidence or []),
                Jsonb(list_payload),
            ),
        ).fetchone()
    return bool(row[0])


def first_payload_value(payload: dict[str, Any], keys: tuple[str, ...]) -> Any:
    for key in keys:
        value = payload.get(key)
        if value not in (None, ""):
            return value
    return None


def update_order_detail(
    database_url: str,
    *,
    shop_key: str,
    order_no: str,
    detail_payload: dict[str, Any],
    order_status: str | None = None,
    order_status_label: str | None = None,
    order_status_normalized: str = "unknown",
    order_type: str | None = None,
    order_type_label: str | None = None,
    return_detected: bool = False,
    return_status: str = "none",
    order_return_time: str | None = None,
    return_evidence: list[dict[str, Any]] | None = None,
) -> None:
    with connect(database_url) as conn:
        conn.execute(
            """
            UPDATE shein_orders
            SET detail_payload = %s,
                order_status = COALESCE(%s, shein_orders.order_status),
                order_status_label = COALESCE(%s, shein_orders.order_status_label),
                order_type = COALESCE(%s, shein_orders.order_type),
                order_type_label = COALESCE(%s, shein_orders.order_type_label),
                order_status_normalized = CASE
                    WHEN %s <> 'unknown' THEN %s
                    ELSE shein_orders.order_status_normalized
                END,
                return_detected = %s OR shein_orders.return_detected,
                return_status = CASE
                    WHEN %s <> 'none' THEN %s
                    ELSE shein_orders.return_status
                END,
                order_return_time = COALESCE(%s, shein_orders.order_return_time),
                return_evidence = CASE
                    WHEN %s <> '[]'::jsonb THEN %s
                    ELSE shein_orders.return_evidence
                END,
                detail_fetched_at = now(),
                last_seen_at = now()
            WHERE shop_key = %s AND order_no = %s
            """,
            (
                Jsonb(detail_payload),
                order_status,
                order_status_label,
                order_type,
                order_type_label,
                order_status_normalized,
                order_status_normalized,
                return_detected,
                return_status,
                return_status,
                order_return_time,
                Jsonb(return_evidence or []),
                Jsonb(return_evidence or []),
                shop_key,
                order_no,
            ),
        )



def backfill_order_metadata(database_url: str, *, shop_key: str | None = None) -> dict[str, int]:
    from .order_statuses import order_status_label, order_status_normalized
    from .order_types import normalize_order_type, order_type_label

    filters = []
    params: list[Any] = []
    if shop_key:
        filters.append("shop_key = %s")
        params.append(shop_key)
    where_sql = f"WHERE {' AND '.join(filters)}" if filters else ""

    total = 0
    updated = 0
    with connect(database_url) as conn:
        rows = conn.execute(
            f"""
            SELECT id, order_status, list_payload, detail_payload
            FROM shein_orders
            {where_sql}
            ORDER BY id
            """,
            params,
        ).fetchall()
        for row in rows:
            total += 1
            order_id = int(row[0])
            raw_order_status = row[1]
            list_payload = row[2] if isinstance(row[2], dict) else None
            detail_payload = row[3] if isinstance(row[3], dict) else None
            if raw_order_status in (None, ""):
                if isinstance(detail_payload, dict):
                    raw_order_status = first_payload_value(
                        detail_payload,
                        ("orderStatus", "order_status", "status", "newGoodsStatus"),
                    )
                if raw_order_status in (None, "") and isinstance(list_payload, dict):
                    raw_order_status = first_payload_value(
                        list_payload,
                        ("orderStatus", "order_status", "status", "newGoodsStatus"),
                    )
            raw_order_status = str(raw_order_status) if raw_order_status not in (None, "") else None

            raw_order_type = None
            if isinstance(detail_payload, dict):
                raw_order_type = detail_payload.get("orderType")
            if raw_order_type in (None, "") and isinstance(list_payload, dict):
                raw_order_type = list_payload.get("orderType")
            normalized_order_type = normalize_order_type(raw_order_type)
            order_type_zh = order_type_label(normalized_order_type) if normalized_order_type else None
            order_status_zh = order_status_label(raw_order_status) if raw_order_status else None
            normalized_order_status = order_status_normalized(raw_order_status)
            result = conn.execute(
                """
                UPDATE shein_orders
                SET order_status = %s,
                    order_status_label = %s,
                    order_status_normalized = %s,
                    order_type = %s,
                    order_type_label = %s,
                    return_detected = false,
                    return_status = 'none',
                    order_return_time = NULL,
                    return_evidence = '[]'::jsonb
                WHERE id = %s
                  AND (
                    order_status IS DISTINCT FROM %s
                    OR order_status_label IS DISTINCT FROM %s
                    OR order_status_normalized IS DISTINCT FROM %s
                    OR order_type IS DISTINCT FROM %s
                    OR order_type_label IS DISTINCT FROM %s
                    OR return_detected IS DISTINCT FROM false
                    OR return_status IS DISTINCT FROM 'none'
                    OR order_return_time IS NOT NULL
                    OR return_evidence IS DISTINCT FROM '[]'::jsonb
                  )
                """,
                (
                    raw_order_status,
                    order_status_zh,
                    normalized_order_status,
                    normalized_order_type,
                    order_type_zh,
                    order_id,
                    raw_order_status,
                    order_status_zh,
                    normalized_order_status,
                    normalized_order_type,
                    order_type_zh,
                ),
            )
            updated += result.rowcount or 0
    return {"total": total, "updated": updated}


def backfill_order_returns(database_url: str, *, shop_key: str | None = None) -> dict[str, int]:
    # Backward-compatible command name. It no longer infers returns from order JSON.
    return backfill_order_metadata(database_url, shop_key=shop_key)


def upsert_return_application(
    database_url: str,
    *,
    shop_key: str,
    return_plan_no: str,
    raw_payload: dict[str, Any],
    status: str | None = None,
    status_label: str | None = None,
    return_reason_type: str | None = None,
    return_reason_label: str | None = None,
    return_deal_type: str | None = None,
    return_deal_label: str | None = None,
    initiator: str | None = None,
    initiator_label: str | None = None,
    return_time: str | None = None,
    update_time: str | None = None,
    related_orders: dict[str, Any] | None = None,
    return_order_nos: list[str] | None = None,
) -> bool:
    with connect(database_url) as conn:
        row = conn.execute(
            """
            INSERT INTO shein_return_applications (
                shop_key, return_plan_no, status, status_label, return_reason_type,
                return_reason_label, return_deal_type, return_deal_label, initiator,
                initiator_label, return_time, update_time, related_orders, return_order_nos,
                raw_payload
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (shop_key, return_plan_no) DO UPDATE SET
                status = COALESCE(EXCLUDED.status, shein_return_applications.status),
                status_label = COALESCE(EXCLUDED.status_label, shein_return_applications.status_label),
                return_reason_type = COALESCE(EXCLUDED.return_reason_type, shein_return_applications.return_reason_type),
                return_reason_label = COALESCE(EXCLUDED.return_reason_label, shein_return_applications.return_reason_label),
                return_deal_type = COALESCE(EXCLUDED.return_deal_type, shein_return_applications.return_deal_type),
                return_deal_label = COALESCE(EXCLUDED.return_deal_label, shein_return_applications.return_deal_label),
                initiator = COALESCE(EXCLUDED.initiator, shein_return_applications.initiator),
                initiator_label = COALESCE(EXCLUDED.initiator_label, shein_return_applications.initiator_label),
                return_time = COALESCE(EXCLUDED.return_time, shein_return_applications.return_time),
                update_time = COALESCE(EXCLUDED.update_time, shein_return_applications.update_time),
                related_orders = EXCLUDED.related_orders,
                return_order_nos = EXCLUDED.return_order_nos,
                raw_payload = EXCLUDED.raw_payload,
                last_seen_at = now()
            RETURNING (xmax = 0) AS inserted
            """,
            (
                shop_key,
                return_plan_no,
                status,
                status_label,
                return_reason_type,
                return_reason_label,
                return_deal_type,
                return_deal_label,
                initiator,
                initiator_label,
                return_time,
                update_time,
                Jsonb(related_orders or {}),
                Jsonb(return_order_nos or []),
                Jsonb(raw_payload),
            ),
        ).fetchone()
    return bool(row[0])


def upsert_order_return(
    database_url: str,
    *,
    shop_key: str,
    return_no: str,
    raw_payload: dict[str, Any],
    order_no: str | None = None,
    return_status: str | None = None,
    return_status_label: str | None = None,
    no_return_goods_sign: str | None = None,
    return_order_tag_code: str | None = None,
    site: str | None = None,
    platform_express_no: str | None = None,
    member_express_no: str | None = None,
    express_company_name: str | None = None,
    performance_cost: Any = None,
    invoice_status: str | None = None,
    request_return_time: str | None = None,
    allocate_time: str | None = None,
    last_update_time: str | None = None,
    seller_signed_time: str | None = None,
    cancel_time: str | None = None,
    completed_time: str | None = None,
    check_status: str | None = None,
    stock_mode: str | None = None,
    receive_type: str | None = None,
    refund_order_nos: list[str] | None = None,
    return_goods_info_list: list[dict[str, Any]] | None = None,
) -> bool:
    with connect(database_url) as conn:
        row = conn.execute(
            """
            INSERT INTO shein_order_returns (
                shop_key, return_no, order_no, return_status, return_status_label,
                no_return_goods_sign, return_order_tag_code, site, platform_express_no,
                member_express_no, express_company_name, performance_cost, invoice_status,
                request_return_time, allocate_time, last_update_time, seller_signed_time,
                cancel_time, completed_time, check_status, stock_mode, receive_type,
                refund_order_nos, return_goods_info_list, raw_payload
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (shop_key, return_no) DO UPDATE SET
                order_no = COALESCE(EXCLUDED.order_no, shein_order_returns.order_no),
                return_status = COALESCE(EXCLUDED.return_status, shein_order_returns.return_status),
                return_status_label = COALESCE(EXCLUDED.return_status_label, shein_order_returns.return_status_label),
                no_return_goods_sign = COALESCE(EXCLUDED.no_return_goods_sign, shein_order_returns.no_return_goods_sign),
                return_order_tag_code = COALESCE(EXCLUDED.return_order_tag_code, shein_order_returns.return_order_tag_code),
                site = COALESCE(EXCLUDED.site, shein_order_returns.site),
                platform_express_no = COALESCE(EXCLUDED.platform_express_no, shein_order_returns.platform_express_no),
                member_express_no = COALESCE(EXCLUDED.member_express_no, shein_order_returns.member_express_no),
                express_company_name = COALESCE(EXCLUDED.express_company_name, shein_order_returns.express_company_name),
                performance_cost = COALESCE(EXCLUDED.performance_cost, shein_order_returns.performance_cost),
                invoice_status = COALESCE(EXCLUDED.invoice_status, shein_order_returns.invoice_status),
                request_return_time = COALESCE(EXCLUDED.request_return_time, shein_order_returns.request_return_time),
                allocate_time = COALESCE(EXCLUDED.allocate_time, shein_order_returns.allocate_time),
                last_update_time = COALESCE(EXCLUDED.last_update_time, shein_order_returns.last_update_time),
                seller_signed_time = COALESCE(EXCLUDED.seller_signed_time, shein_order_returns.seller_signed_time),
                cancel_time = COALESCE(EXCLUDED.cancel_time, shein_order_returns.cancel_time),
                completed_time = COALESCE(EXCLUDED.completed_time, shein_order_returns.completed_time),
                check_status = COALESCE(EXCLUDED.check_status, shein_order_returns.check_status),
                stock_mode = COALESCE(EXCLUDED.stock_mode, shein_order_returns.stock_mode),
                receive_type = COALESCE(EXCLUDED.receive_type, shein_order_returns.receive_type),
                refund_order_nos = EXCLUDED.refund_order_nos,
                return_goods_info_list = EXCLUDED.return_goods_info_list,
                raw_payload = EXCLUDED.raw_payload,
                last_seen_at = now()
            RETURNING (xmax = 0) AS inserted
            """,
            (
                shop_key,
                return_no,
                order_no,
                return_status,
                return_status_label,
                no_return_goods_sign,
                return_order_tag_code,
                site,
                platform_express_no,
                member_express_no,
                express_company_name,
                performance_cost,
                invoice_status,
                request_return_time,
                allocate_time,
                last_update_time,
                seller_signed_time,
                cancel_time,
                completed_time,
                check_status,
                stock_mode,
                receive_type,
                Jsonb(refund_order_nos or []),
                Jsonb(return_goods_info_list or []),
                Jsonb(raw_payload),
            ),
        ).fetchone()
    return bool(row[0])


def reset_order_return_flags(database_url: str, *, shop_key: str | None = None) -> int:
    filters = []
    params: list[Any] = []
    if shop_key:
        filters.append("shop_key = %s")
        params.append(shop_key)
    where_sql = f"WHERE {' AND '.join(filters)}" if filters else ""
    with connect(database_url) as conn:
        result = conn.execute(
            f"""
            UPDATE shein_orders
            SET return_detected = false,
                return_status = 'none',
                order_return_time = NULL,
                return_evidence = '[]'::jsonb
            {where_sql}
            """,
            params,
        )
    return result.rowcount or 0

def ensure_order_full_sync_job(
    database_url: str,
    *,
    shop_key: str,
    sync_key: str,
    query_type: int,
    start_time: str,
    end_time: str,
    base_params: dict[str, Any],
    window_hours: float,
    list_rps: float,
    detail_rps: float,
    reset: bool = False,
) -> int:
    with connect(database_url) as conn:
        row = conn.execute(
            """
            SELECT id, query_type, start_time, end_time, base_params
            FROM shein_order_full_sync_jobs
            WHERE shop_key = %s AND sync_key = %s
            """,
            (shop_key, sync_key),
        ).fetchone()
        if row:
            job_id = int(row[0])
            same_parameters = (
                int(row[1]) == query_type
                and row[2] == start_time
                and row[3] == end_time
                and (row[4] or {}) == base_params
            )
            if not same_parameters and not reset:
                raise ValueError(
                    "sync_key already exists with different parameters; use another --sync-key or pass --reset"
                )
            if reset:
                conn.execute("DELETE FROM shein_order_full_sync_windows WHERE job_id = %s", (job_id,))
                conn.execute(
                    """
                    UPDATE shein_order_full_sync_jobs
                    SET query_type = %s,
                        start_time = %s,
                        end_time = %s,
                        base_params = %s,
                        status = 'running',
                        finished_at = NULL,
                        updated_at = now(),
                        last_error = NULL,
                        window_hours = %s,
                        list_rps = %s,
                        detail_rps = %s
                    WHERE id = %s
                    """,
                    (
                        query_type,
                        start_time,
                        end_time,
                        Jsonb(base_params),
                        window_hours,
                        list_rps,
                        detail_rps,
                        job_id,
                    ),
                )
            else:
                conn.execute(
                    """
                    UPDATE shein_order_full_sync_jobs
                    SET status = CASE WHEN status = 'success' THEN status ELSE 'running' END,
                        finished_at = CASE WHEN status = 'success' THEN finished_at ELSE NULL END,
                        updated_at = now(),
                        last_error = CASE WHEN status = 'success' THEN last_error ELSE NULL END,
                        window_hours = %s, list_rps = %s, detail_rps = %s
                    WHERE id = %s
                    """,
                    (window_hours, list_rps, detail_rps, job_id),
                )
            return job_id

        row = conn.execute(
            """
            INSERT INTO shein_order_full_sync_jobs (
                shop_key, sync_key, query_type, start_time, end_time, base_params,
                window_hours, list_rps, detail_rps, status
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, 'running')
            RETURNING id
            """,
            (
                shop_key,
                sync_key,
                query_type,
                start_time,
                end_time,
                Jsonb(base_params),
                window_hours,
                list_rps,
                detail_rps,
            ),
        ).fetchone()
    return int(row[0])


def ensure_order_full_sync_windows(
    database_url: str,
    *,
    job_id: int,
    windows: list[tuple[int, str, str]],
) -> None:
    with connect(database_url) as conn:
        for window_index, start_time, end_time in windows:
            conn.execute(
                """
                INSERT INTO shein_order_full_sync_windows (job_id, window_index, start_time, end_time)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (job_id, window_index) DO NOTHING
                """,
                (job_id, window_index, start_time, end_time),
            )


def create_order_full_sync_continuation_window(
    database_url: str,
    *,
    job_id: int,
    start_time: str,
    end_time: str,
) -> None:
    with connect(database_url) as conn:
        existing = conn.execute(
            """
            SELECT id
            FROM shein_order_full_sync_windows
            WHERE job_id = %s AND start_time = %s AND end_time = %s
            """,
            (job_id, start_time, end_time),
        ).fetchone()
        if existing:
            return
        row = conn.execute(
            "SELECT COALESCE(MAX(window_index), 0) + 1 FROM shein_order_full_sync_windows WHERE job_id = %s",
            (job_id,),
        ).fetchone()
        conn.execute(
            """
            INSERT INTO shein_order_full_sync_windows (job_id, window_index, start_time, end_time)
            VALUES (%s, %s, %s, %s)
            """,
            (job_id, int(row[0]), start_time, end_time),
        )


def get_pending_order_full_sync_windows(database_url: str, *, job_id: int) -> list[OrderFullSyncWindow]:
    with connect(database_url) as conn:
        rows = conn.execute(
            """
            SELECT id, window_index, start_time, end_time, status, next_page
            FROM shein_order_full_sync_windows
            WHERE job_id = %s AND status <> 'success'
            ORDER BY window_index
            """,
            (job_id,),
        ).fetchall()
    return [
        OrderFullSyncWindow(
            id=int(row[0]),
            window_index=int(row[1]),
            start_time=row[2],
            end_time=row[3],
            status=row[4],
            next_page=int(row[5]),
        )
        for row in rows
    ]


def start_order_full_sync_window(database_url: str, *, window_id: int) -> None:
    with connect(database_url) as conn:
        conn.execute(
            """
            UPDATE shein_order_full_sync_windows
            SET status = 'running',
                started_at = COALESCE(started_at, now()),
                finished_at = NULL,
                updated_at = now(),
                last_error = NULL
            WHERE id = %s
            """,
            (window_id,),
        )


def complete_order_full_sync_window_page(
    database_url: str,
    *,
    window_id: int,
    next_page: int,
    orders_seen_delta: int,
    orders_upserted_delta: int,
    details_fetched_delta: int,
    detail_batches_delta: int,
) -> None:
    with connect(database_url) as conn:
        conn.execute(
            """
            UPDATE shein_order_full_sync_windows
            SET next_page = %s,
                pages = pages + 1,
                orders_seen = orders_seen + %s,
                orders_upserted = orders_upserted + %s,
                details_fetched = details_fetched + %s,
                detail_batches = detail_batches + %s,
                updated_at = now()
            WHERE id = %s
            """,
            (
                next_page,
                orders_seen_delta,
                orders_upserted_delta,
                details_fetched_delta,
                detail_batches_delta,
                window_id,
            ),
        )


def finish_order_full_sync_window(
    database_url: str,
    *,
    window_id: int,
    status: str,
    error: str | None = None,
) -> None:
    with connect(database_url) as conn:
        conn.execute(
            """
            UPDATE shein_order_full_sync_windows
            SET status = %s,
                finished_at = CASE WHEN %s IN ('success', 'failed') THEN now() ELSE finished_at END,
                updated_at = now(),
                last_error = %s
            WHERE id = %s
            """,
            (status, status, error, window_id),
        )


def finish_order_full_sync_job(
    database_url: str,
    *,
    job_id: int,
    status: str,
    error: str | None = None,
) -> None:
    with connect(database_url) as conn:
        conn.execute(
            """
            UPDATE shein_order_full_sync_jobs
            SET status = %s,
                finished_at = CASE WHEN %s IN ('success', 'failed') THEN now() ELSE finished_at END,
                updated_at = now(),
                last_error = %s
            WHERE id = %s
            """,
            (status, status, error, job_id),
        )


def get_order_full_sync_summary(database_url: str, *, job_id: int) -> dict[str, Any]:
    with connect(database_url) as conn:
        row = conn.execute(
            """
            SELECT
                j.id,
                j.sync_key,
                j.status,
                COUNT(w.id) AS windows_total,
                COUNT(w.id) FILTER (WHERE w.status = 'success') AS windows_completed,
                COALESCE(SUM(w.pages), 0) AS pages,
                COALESCE(SUM(w.orders_seen), 0) AS orders_seen,
                COALESCE(SUM(w.orders_upserted), 0) AS orders_upserted,
                COALESCE(SUM(w.details_fetched), 0) AS details_fetched,
                j.last_error
            FROM shein_order_full_sync_jobs j
            LEFT JOIN shein_order_full_sync_windows w ON w.job_id = j.id
            WHERE j.id = %s
            GROUP BY j.id
            """,
            (job_id,),
        ).fetchone()
    if not row:
        raise KeyError(f"full sync job not found: {job_id}")
    return {
        "jobId": int(row[0]),
        "syncKey": row[1],
        "status": row[2],
        "windowsTotal": int(row[3]),
        "windowsCompleted": int(row[4]),
        "pages": int(row[5]),
        "ordersSeen": int(row[6]),
        "ordersInserted": int(row[7]),
        "detailsFetched": int(row[8]),
        "error": row[9],
    }


def get_order_full_sync_summary_by_key(database_url: str, *, shop_key: str, sync_key: str) -> dict[str, Any]:
    with connect(database_url) as conn:
        row = conn.execute(
            """
            SELECT id
            FROM shein_order_full_sync_jobs
            WHERE shop_key = %s AND sync_key = %s
            """,
            (shop_key, sync_key),
        ).fetchone()
    if not row:
        raise KeyError(f"full sync job not found: {shop_key}/{sync_key}")
    return get_order_full_sync_summary(database_url, job_id=int(row[0]))
